import { createSlice } from '@reduxjs/toolkit';
import { ALLOWED_DEPARTMENTS, isValidDepartment, mapLegacyDepartment } from '../constants/departments.js';

export const initialAssets = [
  // =========================================================================
  // 1. COMPUTER SCIENCE (CS)
  // =========================================================================
  {
    id: 'AST-001',
    name: 'Ergonomic High-Back Mesh Task Chair',
    mainCategory: 'Furniture',
    category: 'Chair',
    itemType: 'Task Chair',
    building: 'Engineering Block',
    department: 'Computer Science',
    room: 'CS-Lab1',
    assignedTo: 'Prof. Suresh Babu',
    assignedRole: 'Lab In-Charge & Faculty',
    assignedEmail: 'suresh.babu@nec.edu.in',
    condition: 'Good',
    status: 'In Use',
    purchaseDate: '2024-03-12',
    cost: 5400,
    supplier: 'Featherlite Seating Ltd',
    warranty: '3 Years (Till Mar 2027)',
    quantity: 40,
    description: 'High-back breathable mesh task chairs with adjustable lumbar support and pneumatic height lift for CS Lab workstations.',
  },
  {
    id: 'AST-002',
    name: 'Student Chair with Wooden Writing Pad',
    mainCategory: 'Furniture',
    category: 'Chair',
    itemType: 'Student Chair with Writing Pad',
    building: 'Engineering Block',
    department: 'Computer Science',
    room: 'CS-101',
    assignedTo: 'Prof. Anitha Sharma',
    assignedRole: 'Classroom Coordinator',
    assignedEmail: 'anitha.sharma@nec.edu.in',
    condition: 'Good',
    status: 'In Use',
    purchaseDate: '2023-08-10',
    cost: 2100,
    supplier: 'Godrej Interio',
    warranty: '2 Years (Till Aug 2025)',
    quantity: 60,
    description: 'Heavy-duty steel tubular framed student lecture chairs with laminated writing pad and lower wire storage basket.',
  },
  {
    id: 'AST-008',
    name: 'Dual Seater Integrated Student Desk & Bench',
    mainCategory: 'Furniture',
    category: 'Table',
    itemType: 'Student Bench',
    building: 'Engineering Block',
    department: 'Computer Science',
    room: 'CS-102',
    assignedTo: 'Prof. Anitha Sharma',
    assignedRole: 'Dept Admin',
    assignedEmail: 'anitha.sharma@nec.edu.in',
    condition: 'Good',
    status: 'In Use',
    purchaseDate: '2023-06-25',
    cost: 4800,
    supplier: 'Godrej Interio',
    warranty: '3 Years (Till Jun 2026)',
    quantity: 30,
    description: 'Two-seater integrated dual desk-bench with rounded edge PVC beading, bag hooks, and under-desk book rack.',
  },
  {
    id: 'AST-014',
    name: '4-Drawer Vertical Heavy Duty Steel Filing Cabinet',
    mainCategory: 'Furniture',
    category: 'Cupboard & Storage',
    itemType: 'Filing Cabinet',
    building: 'Engineering Block',
    department: 'Computer Science',
    room: 'CS-101',
    assignedTo: 'Prof. Anitha Sharma',
    assignedRole: 'Department Administrator',
    assignedEmail: 'anitha.sharma@nec.edu.in',
    condition: 'Good',
    status: 'In Use',
    purchaseDate: '2023-05-15',
    cost: 9800,
    supplier: 'Godrej Interio',
    warranty: '3 Years (Till May 2026)',
    quantity: 5,
    description: 'Centralized locking telescopic ball-bearing runner vertical filing cabinet for confidential student records.',
  },
  {
    id: 'AST-017',
    name: '18-Locker Personal Student Belongings Locker Unit',
    mainCategory: 'Furniture',
    category: 'Cupboard & Storage',
    itemType: 'Locker',
    building: 'Engineering Block',
    department: 'Computer Science',
    room: 'CS-Lab1',
    assignedTo: 'Prof. Suresh Babu',
    assignedRole: 'Lab In-Charge',
    assignedEmail: 'suresh.babu@nec.edu.in',
    condition: 'Fair',
    status: 'In Use',
    purchaseDate: '2024-05-02',
    cost: 26000,
    supplier: 'Godrej Security',
    warranty: '3 Years (Till May 2027)',
    quantity: 4,
    description: 'Individual key and padlock-compatible personal student lockers with louvers for internal air ventilation.',
  },
  {
    id: 'AST-019',
    name: 'Acoustic Wooden Podium / Lectern with Mic Mount',
    mainCategory: 'Furniture',
    category: 'Other Furniture',
    itemType: 'Lectern',
    building: 'Engineering Block',
    department: 'Computer Science',
    room: 'CS-101',
    assignedTo: 'Prof. Anitha Sharma',
    assignedRole: 'Lecture In-Charge',
    assignedEmail: 'anitha.sharma@nec.edu.in',
    condition: 'Good',
    status: 'In Use',
    purchaseDate: '2023-07-19',
    cost: 11000,
    supplier: 'Ahuja Sound Systems',
    warranty: '2 Years (Till Jul 2025)',
    quantity: 2,
    description: 'Teak wood teacher podium with gooseneck microphone XLR socket and integrated reading light fixture.',
  },
  {
    id: 'AST-021',
    name: 'Lockable Acrylic Shutter Pinup Notice Board (6x4 ft)',
    mainCategory: 'Furniture',
    category: 'Other Furniture',
    itemType: 'Notice Board',
    building: 'Engineering Block',
    department: 'Computer Science',
    room: 'CS-101',
    assignedTo: 'Prof. Suresh Babu',
    assignedRole: 'Student Affairs Coordinator',
    assignedEmail: 'suresh.babu@nec.edu.in',
    condition: 'Fair',
    status: 'In Use',
    purchaseDate: '2023-03-10',
    cost: 3600,
    supplier: 'Alkosign Display Systems',
    warranty: '1 Year Standard',
    quantity: 6,
    description: 'Anodized aluminium framed high-density felt pinboard with sliding clear acrylic shutter and security lock.',
  },
  {
    id: 'AST-023',
    name: 'Logitech Brio 4K Ultra-HD Auto-Framing Webcam',
    mainCategory: 'Teaching Equipment',
    category: 'Camera & AV',
    itemType: 'Web cam',
    building: 'Engineering Block',
    department: 'Computer Science',
    room: 'CS-Lab1',
    assignedTo: 'Prof. Suresh Babu',
    assignedRole: 'Online Lecture In-Charge',
    assignedEmail: 'suresh.babu@nec.edu.in',
    condition: 'Good',
    status: 'In Use',
    purchaseDate: '2024-02-18',
    cost: 18500,
    supplier: 'Logitech India',
    warranty: '3 Years (Till Feb 2027)',
    quantity: 4,
    description: '4K HDR webcam with AI face auto-tracking, dual noise-cancelling microphones and privacy shutter.',
  },
  {
    id: 'AST-025',
    name: 'Magnetic Ceramic Non-Ghosting Whiteboard (8x4 ft)',
    mainCategory: 'Teaching Equipment',
    category: 'Boards',
    itemType: 'Whiteboard',
    building: 'Engineering Block',
    department: 'Computer Science',
    room: 'CS-102',
    assignedTo: 'Prof. Anitha Sharma',
    assignedRole: 'Faculty Coordinator',
    assignedEmail: 'anitha.sharma@nec.edu.in',
    condition: 'Good',
    status: 'In Use',
    purchaseDate: '2024-01-20',
    cost: 5200,
    supplier: 'Alkosign Systems',
    warranty: '5 Years Surface (Till Jan 2029)',
    quantity: 4,
    description: 'Porcelain enameled steel surface with aluminum trim, ABS corners, and integrated full-width dry-erase marker tray.',
  },
  {
    id: 'AST-029',
    name: 'Epson 4200 Lumens WUXGA 3LCD Classroom Projector',
    mainCategory: 'Teaching Equipment',
    category: 'Projector',
    itemType: 'LCD Projector',
    building: 'Engineering Block',
    department: 'Computer Science',
    room: 'CS-101',
    assignedTo: 'Prof. Anitha Sharma',
    assignedRole: 'Faculty In-Charge',
    assignedEmail: 'anitha.sharma@nec.edu.in',
    condition: 'Fair',
    status: 'In Use',
    purchaseDate: '2023-02-18',
    cost: 48000,
    supplier: 'Epson India Pvt Ltd',
    warranty: '2 Years (Till Feb 2025)',
    quantity: 1,
    description: 'Full HD WUXGA 3LCD ceiling mounted projector with dual HDMI, USB viewer, and Miracast wireless casting.',
  },
  {
    id: 'AST-033',
    name: 'Shure SM58 Cardioid Dynamic Wired Vocal Microphone',
    mainCategory: 'Teaching Equipment',
    category: 'Microphone',
    itemType: 'Wired Microphone',
    building: 'Engineering Block',
    department: 'Computer Science',
    room: 'CS-101',
    assignedTo: 'Prof. Anitha Sharma',
    assignedRole: 'Dept Coordinator',
    assignedEmail: 'anitha.sharma@nec.edu.in',
    condition: 'Good',
    status: 'In Use',
    purchaseDate: '2023-06-15',
    cost: 8900,
    supplier: 'Shure Audio India',
    warranty: '2 Years (Till Jun 2025)',
    quantity: 2,
    description: 'Industry standard cardioid vocal microphone with 10-meter balanced low-noise XLR cable and shock mount clip.',
  },
  {
    id: 'AST-044',
    name: 'Dell Precision Core i9 AI Developer Workstation Tower',
    mainCategory: 'Teaching Equipment',
    category: 'Camera & AV',
    itemType: 'AI Workstation',
    building: 'Engineering Block',
    department: 'Computer Science',
    room: 'CS-Lab1',
    assignedTo: 'Prof. Suresh Babu',
    assignedRole: 'AI Lab In-Charge',
    assignedEmail: 'suresh.babu@nec.edu.in',
    condition: 'Good',
    status: 'In Use',
    purchaseDate: '2024-04-15',
    cost: 245000,
    supplier: 'Dell India Enterprise',
    warranty: '3 Years Comprehensive (Till Apr 2027)',
    quantity: 35,
    description: 'Liquid-cooled 64-core high-performance computing tower with dual RTX 4090 GPUs and 128GB DDR5 RAM for machine learning models.',
  },
  {
    id: 'AST-045',
    name: 'Dell PowerEdge R750 2U Rackmount Dual Xeon High-Compute Server',
    mainCategory: 'Teaching Equipment',
    category: 'Camera & AV',
    itemType: 'Server Rack',
    building: 'Engineering Block',
    department: 'Computer Science',
    room: 'CS-Lab1',
    assignedTo: 'Prof. Anitha Sharma',
    assignedRole: 'Department Administrator',
    assignedEmail: 'anitha.sharma@nec.edu.in',
    condition: 'Good',
    status: 'In Use',
    purchaseDate: '2023-11-20',
    cost: 480000,
    supplier: 'Dell India Enterprise',
    warranty: '5 Years ProSupport (Till Nov 2028)',
    quantity: 2,
    description: 'Dual Intel Xeon Gold 32-core rack server with 256GB ECC RAM and 16TB NVMe SSD storage array for departmental cloud.',
  },
  {
    id: 'AST-046',
    name: 'Cisco Catalyst 48-Port Layer-3 Managed Gigabit PoE+ Switch',
    mainCategory: 'Teaching Equipment',
    category: 'Camera & AV',
    itemType: 'Network Switch',
    building: 'Engineering Block',
    department: 'Computer Science',
    room: 'CS-Lab1',
    assignedTo: 'Prof. Suresh Babu',
    assignedRole: 'Network Lab Coordinator',
    assignedEmail: 'suresh.babu@nec.edu.in',
    condition: 'Good',
    status: 'In Use',
    purchaseDate: '2023-08-10',
    cost: 125000,
    supplier: 'Cisco Systems India',
    warranty: 'Lifetime Limited Hardware',
    quantity: 6,
    description: '48-port 10/100/1000 Gigabit PoE+ Layer 3 enterprise rackmount switch with 4x 10G SFP+ uplinks.',
  },
  {
    id: 'AST-047',
    name: 'HP LaserJet Enterprise Duplex Network Workgroup Printer',
    mainCategory: 'Teaching Equipment',
    category: 'Camera & AV',
    itemType: 'Laser Printer',
    building: 'Engineering Block',
    department: 'Computer Science',
    room: 'CS-101',
    assignedTo: 'Prof. Anitha Sharma',
    assignedRole: 'Office Administrator',
    assignedEmail: 'anitha.sharma@nec.edu.in',
    condition: 'Good',
    status: 'In Use',
    purchaseDate: '2023-05-18',
    cost: 45000,
    supplier: 'HP India Sales',
    warranty: '3 Years Onsite (Till May 2026)',
    quantity: 3,
    description: 'Heavy duty 55ppm duplex monochrome laser printer with Gigabit Ethernet and PIN secure printing.',
  },

  // =========================================================================
  // 2. MECHANICAL (ME)
  // =========================================================================
  {
    id: 'AST-003',
    name: 'Moulded Polypropylene Student Chair',
    mainCategory: 'Furniture',
    category: 'Chair',
    itemType: 'Student Chair',
    building: 'Engineering Block',
    department: 'Mechanical',
    room: 'ME-101',
    assignedTo: 'Prof. Kavitha Raj',
    assignedRole: 'Dept Coordinator',
    assignedEmail: 'kavitha.raj@nec.edu.in',
    condition: 'Fair',
    status: 'In Use',
    purchaseDate: '2022-07-20',
    cost: 1450,
    supplier: 'Nilkamal Industries',
    warranty: '1 Year Standard',
    quantity: 65,
    description: 'Stackable high-durability polymer chairs with MS powder-coated legs for engineering workshops and classrooms.',
  },
  {
    id: 'AST-026',
    name: 'Vitreous Steel Anti-Glare Green Chalkboard (8x4 ft)',
    mainCategory: 'Teaching Equipment',
    category: 'Boards',
    itemType: 'Green Board',
    building: 'Engineering Block',
    department: 'Mechanical',
    room: 'ME-101',
    assignedTo: 'Prof. Kavitha Raj',
    assignedRole: 'Dept Coordinator',
    assignedEmail: 'kavitha.raj@nec.edu.in',
    condition: 'Poor',
    status: 'Needs Inspection',
    purchaseDate: '2022-08-14',
    cost: 3900,
    supplier: 'Whitemark Boards',
    warranty: '2 Years Standard',
    quantity: 4,
    description: 'Heavy-duty ceramic vitreous steel green chalkboard with anti-glare matte finish for traditional mathematics and mechanics.',
  },
  {
    id: 'AST-038',
    name: 'Crompton 450mm High-Velocity Heavy Wall Fan',
    mainCategory: 'Electricals',
    category: 'Fans & Cooling',
    itemType: 'Wall Fan',
    building: 'Engineering Block',
    department: 'Mechanical',
    room: 'ME-101',
    assignedTo: 'Prof. Kavitha Raj',
    assignedRole: 'Lab Supervisor',
    assignedEmail: 'kavitha.raj@nec.edu.in',
    condition: 'Poor',
    status: 'Needs Inspection',
    purchaseDate: '2022-09-02',
    cost: 2800,
    supplier: 'Crompton Greaves',
    warranty: '2 Years Standard',
    quantity: 6,
    description: 'Aerodynamic metal blade wall mounted oscillating fan with pull cord controls for high airflow in mechanical shops.',
  },
  {
    id: 'AST-043',
    name: 'Havells 50W High-Bay Industrial LED Light',
    mainCategory: 'Electricals',
    category: 'Lighting',
    itemType: 'LED Light',
    building: 'Engineering Block',
    department: 'Mechanical',
    room: 'ME-101',
    assignedTo: 'Prof. Kavitha Raj',
    assignedRole: 'Workshop In-Charge',
    assignedEmail: 'kavitha.raj@nec.edu.in',
    condition: 'Damaged',
    status: 'Needs Inspection',
    purchaseDate: '2023-04-14',
    cost: 3800,
    supplier: 'Havells India',
    warranty: '3 Years (Till Apr 2026)',
    quantity: 8,
    description: 'Die-cast aluminium high-bay luminaires designed for high-ceiling mechanical workshops and labs.',
  },
  {
    id: 'AST-048',
    name: 'Solid Beechwood Mechanical Workshop Workbench with 6" Vices',
    mainCategory: 'Furniture',
    category: 'Table',
    itemType: 'Workshop Workbench',
    building: 'Engineering Block',
    department: 'Mechanical',
    room: 'ME-Workshop',
    assignedTo: 'Prof. Kavitha Raj',
    assignedRole: 'Workshop In-Charge',
    assignedEmail: 'kavitha.raj@nec.edu.in',
    condition: 'Good',
    status: 'In Use',
    purchaseDate: '2023-02-10',
    cost: 28500,
    supplier: 'Godrej Interio Commercial',
    warranty: '5 Years (Till Feb 2028)',
    quantity: 12,
    description: 'Heavy duty steel framed 75mm thick seasoned beechwood top workbench fitted with twin 6-inch swivel base bench vices.',
  },
  {
    id: 'AST-049',
    name: 'Jyoti CNC High-Precision 3-Axis Vertical Milling Machine Center',
    mainCategory: 'Teaching Equipment',
    category: 'Camera & AV',
    itemType: 'CNC Milling Machine',
    building: 'Engineering Block',
    department: 'Mechanical',
    room: 'ME-Workshop',
    assignedTo: 'Prof. Kavitha Raj',
    assignedRole: 'CAD/CAM Lab Head',
    assignedEmail: 'kavitha.raj@nec.edu.in',
    condition: 'Good',
    status: 'In Use',
    purchaseDate: '2023-10-12',
    cost: 850000,
    supplier: 'Jyoti CNC Automation',
    warranty: '3 Years (Till Oct 2026)',
    quantity: 2,
    description: 'Fanuc 0i-MF Plus CNC controlled 8000 RPM spindle 3-axis VMC for precision metal cutting and tooling practicals.',
  },
  {
    id: 'AST-050',
    name: 'Heavy Duty All-Geared Industrial Lathe Machine (6-Foot Bed)',
    mainCategory: 'Teaching Equipment',
    category: 'Camera & AV',
    itemType: 'Lathe Machine',
    building: 'Engineering Block',
    department: 'Mechanical',
    room: 'ME-Workshop',
    assignedTo: 'Prof. Kavitha Raj',
    assignedRole: 'Workshop In-Charge',
    assignedEmail: 'kavitha.raj@nec.edu.in',
    condition: 'Good',
    status: 'In Use',
    purchaseDate: '2022-11-15',
    cost: 220000,
    supplier: 'Batliboi Machine Tools',
    warranty: '3 Years Standard',
    quantity: 6,
    description: 'Precision grade all-geared head lathe with induction hardened bed ways, 3-jaw self centering chuck, and coolant pump.',
  },
  {
    id: 'AST-051',
    name: 'Pelton Wheel Turbine Fluid Mechanics Laboratory Test Apparatus',
    mainCategory: 'Teaching Equipment',
    category: 'Camera & AV',
    itemType: 'Fluid Mechanics Rig',
    building: 'Engineering Block',
    department: 'Mechanical',
    room: 'ME-102',
    assignedTo: 'Prof. Kavitha Raj',
    assignedRole: 'Fluid Mechanics Supervisor',
    assignedEmail: 'kavitha.raj@nec.edu.in',
    condition: 'Good',
    status: 'In Use',
    purchaseDate: '2023-01-25',
    cost: 175000,
    supplier: 'Edutech Instrumentation',
    warranty: '2 Years Standard',
    quantity: 1,
    description: 'Complete closed-circuit Pelton impulse turbine test rig with multi-stage centrifugal pump, digital flow meter and dynamometer.',
  },
  {
    id: 'AST-052',
    name: 'Thermal Conductivity of Metal Rod Heat Transfer Test Apparatus',
    mainCategory: 'Teaching Equipment',
    category: 'Camera & AV',
    itemType: 'Heat Transfer Rig',
    building: 'Engineering Block',
    department: 'Mechanical',
    room: 'ME-102',
    assignedTo: 'Prof. Kavitha Raj',
    assignedRole: 'Thermal Lab Head',
    assignedEmail: 'kavitha.raj@nec.edu.in',
    condition: 'Good',
    status: 'In Use',
    purchaseDate: '2023-04-18',
    cost: 92000,
    supplier: 'Scientific Educational Instruments',
    warranty: '2 Years Standard',
    quantity: 2,
    description: 'Fourier law steady-state thermal conductivity measurement unit with digital temperature indicator and multichannel thermocouple array.',
  },
  {
    id: 'AST-053',
    name: 'Industrial 7-Drawer Lockable Mobile Mechanic Tool Storage Trolley',
    mainCategory: 'Furniture',
    category: 'Cupboard & Storage',
    itemType: 'Tool Cabinet',
    building: 'Engineering Block',
    department: 'Mechanical',
    room: 'ME-Workshop',
    assignedTo: 'Prof. Kavitha Raj',
    assignedRole: 'Workshop In-Charge',
    assignedEmail: 'kavitha.raj@nec.edu.in',
    condition: 'Good',
    status: 'In Use',
    purchaseDate: '2024-02-14',
    cost: 16500,
    supplier: 'Godrej Interio Commercial',
    warranty: '3 Years (Till Feb 2027)',
    quantity: 8,
    description: 'Heavy gauge steel ball-bearing slider 7-drawer tool cabinet on heavy duty locking rubber castors for workshop tools.',
  },
  {
    id: 'AST-054',
    name: 'Creality Industrial Dual-Extruder High-Temp 3D Rapid Prototyper',
    mainCategory: 'Teaching Equipment',
    category: 'Camera & AV',
    itemType: '3D Printer',
    building: 'Engineering Block',
    department: 'Mechanical',
    room: 'ME-102',
    assignedTo: 'Prof. Kavitha Raj',
    assignedRole: 'Prototyping Lab Head',
    assignedEmail: 'kavitha.raj@nec.edu.in',
    condition: 'Good',
    status: 'In Use',
    purchaseDate: '2024-03-08',
    cost: 115000,
    supplier: 'Creality 3D India',
    warranty: '2 Years (Till Mar 2026)',
    quantity: 3,
    description: 'Enclosed heated chamber FDM 3D printer capable of printing engineering grade Carbon Fiber, PEEK, and ABS filaments.',
  },

  // =========================================================================
  // 3. CIVIL
  // =========================================================================
  {
    id: 'AST-055',
    name: 'A0 Large-Format Dual-Pedestal Architectural Drafting Table with Parallel Motion Ruler',
    mainCategory: 'Furniture',
    category: 'Table',
    itemType: 'Drafting Table',
    building: 'IT Block',
    department: 'Civil',
    room: 'CV-101',
    assignedTo: 'Prof. Aruna Devi',
    assignedRole: 'Civil Dept Administrator',
    assignedEmail: 'aruna.devi@nec.edu.in',
    condition: 'Good',
    status: 'In Use',
    purchaseDate: '2023-07-22',
    cost: 18500,
    supplier: 'Methodex Systems',
    warranty: '5 Years (Till Jul 2028)',
    quantity: 25,
    description: 'Heavy duty height and angle adjustable A0 pine core drawing board with counterbalanced parallel motion ruler wire system.',
  },
  {
    id: 'AST-056',
    name: 'Leica TS07 1-Second High-Precision Reflectorless Total Station Surveying Kit',
    mainCategory: 'Teaching Equipment',
    category: 'Camera & AV',
    itemType: 'Total Station Theodolite',
    building: 'IT Block',
    department: 'Civil',
    room: 'CV-Survey',
    assignedTo: 'Dr. Senthil Kumar',
    assignedRole: 'Head of Civil Engineering',
    assignedEmail: 'senthil.kumar@nec.edu.in',
    condition: 'Good',
    status: 'In Use',
    purchaseDate: '2023-09-10',
    cost: 425000,
    supplier: 'Leica Geosystems India',
    warranty: '3 Years (Till Sep 2026)',
    quantity: 3,
    description: '1-second angle accuracy electronic total station with FlexField onboard survey software, laser plummet, prism, and heavy wooden tripod.',
  },
  {
    id: 'AST-057',
    name: '2000kN Digital Microprocessor-Controlled Concrete Compression Testing Machine (CTM)',
    mainCategory: 'Teaching Equipment',
    category: 'Camera & AV',
    itemType: 'Compression Tester',
    building: 'IT Block',
    department: 'Civil',
    room: 'CV-Lab1',
    assignedTo: 'Prof. Aruna Devi',
    assignedRole: 'Concrete Technology Lab In-Charge',
    assignedEmail: 'aruna.devi@nec.edu.in',
    condition: 'Good',
    status: 'In Use',
    purchaseDate: '2023-03-15',
    cost: 360000,
    supplier: 'HEICO Material Testing Systems',
    warranty: '3 Years (Till Mar 2026)',
    quantity: 2,
    description: 'High rigidity four-column load frame digital compression tester with pace rate indicator for standard concrete cubes and cylinders.',
  },
  {
    id: 'AST-058',
    name: '1000kN Computerized Servo-Hydraulic Universal Testing Machine (UTM) for Rebar & Steel',
    mainCategory: 'Teaching Equipment',
    category: 'Camera & AV',
    itemType: 'Universal Testing Machine',
    building: 'IT Block',
    department: 'Civil',
    room: 'CV-Lab1',
    assignedTo: 'Dr. Senthil Kumar',
    assignedRole: 'Strength of Materials Lab Head',
    assignedEmail: 'senthil.kumar@nec.edu.in',
    condition: 'Good',
    status: 'In Use',
    purchaseDate: '2022-12-05',
    cost: 950000,
    supplier: 'FIE Instruments & Machines',
    warranty: '3 Years Standard',
    quantity: 1,
    description: 'PC-interfaced electronic servo universal testing machine with real-time stress-strain graph plotting and electronic extensometer.',
  },
  {
    id: 'AST-059',
    name: 'Motorized Direct Shear Soil Mechanics Test Apparatus with Electronic Dial Gauges',
    mainCategory: 'Teaching Equipment',
    category: 'Camera & AV',
    itemType: 'Soil Shear Apparatus',
    building: 'IT Block',
    department: 'Civil',
    room: 'CV-Lab1',
    assignedTo: 'Prof. Aruna Devi',
    assignedRole: 'Geotechnical Lab Supervisor',
    assignedEmail: 'aruna.devi@nec.edu.in',
    condition: 'Good',
    status: 'In Use',
    purchaseDate: '2023-06-18',
    cost: 145000,
    supplier: 'Aimil Geotechnical Solutions',
    warranty: '2 Years Standard',
    quantity: 2,
    description: 'Variable speed 72-gear box motorized soil direct shear test apparatus with 60x60mm shear box, proving ring, and load hanger.',
  },
  {
    id: 'AST-060',
    name: 'High-Accuracy Auto Level Surveying Kit with Telescopic Aluminum Staff & Heavy Tripod',
    mainCategory: 'Teaching Equipment',
    category: 'Camera & AV',
    itemType: 'Auto Level Instrument',
    building: 'IT Block',
    department: 'Civil',
    room: 'CV-Survey',
    assignedTo: 'Dr. Senthil Kumar',
    assignedRole: 'Surveying Fieldwork Coordinator',
    assignedEmail: 'senthil.kumar@nec.edu.in',
    condition: 'Good',
    status: 'In Use',
    purchaseDate: '2023-11-04',
    cost: 24500,
    supplier: 'Sokkisha Survey Tech',
    warranty: '2 Years Standard',
    quantity: 6,
    description: '32x magnification air-damped compensator automatic leveling instrument with 5-meter dual-graduated telescopic leveling staff.',
  },
  {
    id: 'AST-061',
    name: 'Standard Slump Cone & Compaction Factor Workability Testing Kit for Fresh Concrete',
    mainCategory: 'Teaching Equipment',
    category: 'Camera & AV',
    itemType: 'Slump Test Apparatus',
    building: 'IT Block',
    department: 'Civil',
    room: 'CV-Lab1',
    assignedTo: 'Prof. Aruna Devi',
    assignedRole: 'Concrete Testing Supervisor',
    assignedEmail: 'aruna.devi@nec.edu.in',
    condition: 'Good',
    status: 'In Use',
    purchaseDate: '2024-01-20',
    cost: 8500,
    supplier: 'Scientific Educational Instruments',
    warranty: '2 Years (Till Jan 2026)',
    quantity: 4,
    description: 'Seamless spun steel slump cone with base plate, standard 16mm bullet-nosed tamping rod and graduated measurement scale.',
  },
  {
    id: 'AST-062',
    name: 'Horizontal Heavy Gauge Steel Architectural Plan & Blueprint Filing Cabinet (6-Drawer)',
    mainCategory: 'Furniture',
    category: 'Cupboard & Storage',
    itemType: 'Blueprint Cabinet',
    building: 'IT Block',
    department: 'Civil',
    room: 'CV-101',
    assignedTo: 'Prof. Aruna Devi',
    assignedRole: 'Drawing Office Custodian',
    assignedEmail: 'aruna.devi@nec.edu.in',
    condition: 'Good',
    status: 'In Use',
    purchaseDate: '2023-08-30',
    cost: 26000,
    supplier: 'Godrej Security & Storage',
    warranty: '5 Years (Till Aug 2028)',
    quantity: 4,
    description: 'A0 horizontal plan file cabinet with nylon roller drawer slides, front paper weight hold-downs, and central plunger lock.',
  },
  {
    id: 'AST-063',
    name: 'Dual-Frequency RTK GNSS GPS Geodetic Survey Receiver with Handheld Controller',
    mainCategory: 'Teaching Equipment',
    category: 'Camera & AV',
    itemType: 'GPS Survey Receiver',
    building: 'IT Block',
    department: 'Civil',
    room: 'CV-Survey',
    assignedTo: 'Dr. Senthil Kumar',
    assignedRole: 'GIS & Remote Sensing Head',
    assignedEmail: 'senthil.kumar@nec.edu.in',
    condition: 'Good',
    status: 'In Use',
    purchaseDate: '2024-02-28',
    cost: 380000,
    supplier: 'Trimble Navigation India',
    warranty: '3 Years (Till Feb 2027)',
    quantity: 2,
    description: 'Multi-constellation RTK GNSS receiver base and rover system with Android survey field controller and carbon fiber pole.',
  },
  {
    id: 'AST-064',
    name: 'Heavy Duty High-Back Hydraulic Lab Stools for Drafting & Testing Stations',
    mainCategory: 'Furniture',
    category: 'Chair',
    itemType: 'Lab Stool',
    building: 'IT Block',
    department: 'Civil',
    room: 'CV-101',
    assignedTo: 'Prof. Aruna Devi',
    assignedRole: 'Drawing Studio Custodian',
    assignedEmail: 'aruna.devi@nec.edu.in',
    condition: 'Good',
    status: 'In Use',
    purchaseDate: '2023-07-22',
    cost: 2900,
    supplier: 'Featherlite Seating Ltd',
    warranty: '3 Years (Till Jul 2026)',
    quantity: 30,
    description: 'Round PU cushioned seat hydraulic drafting stools with 360-degree foot support ring and glide feet.',
  },

  // =========================================================================
  // 4. IT
  // =========================================================================
  {
    id: 'AST-065',
    name: 'Lenovo ThinkCentre Core i7 16GB RAM Desktop Workstations',
    mainCategory: 'Teaching Equipment',
    category: 'Camera & AV',
    itemType: 'Desktop PC',
    building: 'IT Block',
    department: 'IT',
    room: 'IT-Lab1',
    assignedTo: 'Prof. Ramesh Nair',
    assignedRole: 'IT Lab Administrator',
    assignedEmail: 'ramesh.nair@nec.edu.in',
    condition: 'Good',
    status: 'In Use',
    purchaseDate: '2024-01-15',
    cost: 62000,
    supplier: 'Lenovo India Enterprise',
    warranty: '3 Years Onsite (Till Jan 2027)',
    quantity: 45,
    description: 'Intel Core i7 13th Gen desktop towers with 16GB DDR5 RAM, 512GB NVMe SSD, and FHD IPS borderless monitors for IT labs.',
  },
  {
    id: 'AST-066',
    name: 'Dell UltraSharp 27" 4K IPS Color-Accurate Dual Monitors',
    mainCategory: 'Teaching Equipment',
    category: 'Camera & AV',
    itemType: 'LED Monitor',
    building: 'IT Block',
    department: 'IT',
    room: 'IT-Lab1',
    assignedTo: 'Prof. Ramesh Nair',
    assignedRole: 'Web Dev Lab Head',
    assignedEmail: 'ramesh.nair@nec.edu.in',
    condition: 'Good',
    status: 'In Use',
    purchaseDate: '2023-11-10',
    cost: 38000,
    supplier: 'Dell India Enterprise',
    warranty: '3 Years Premium Panel (Till Nov 2026)',
    quantity: 30,
    description: '27-inch 4K UHD 3840x2160 IPS monitors with 99% sRGB color gamut and USB-C 90W power delivery hubs for app development.',
  },
  {
    id: 'AST-067',
    name: 'Fortinet FortiGate Next-Gen Enterprise Security Hardware Firewall',
    mainCategory: 'Teaching Equipment',
    category: 'Camera & AV',
    itemType: 'Network Firewall',
    building: 'IT Block',
    department: 'IT',
    room: 'IT-ServerRoom',
    assignedTo: 'Dr. M. Venkatesh',
    assignedRole: 'Head of Department - IT',
    assignedEmail: 'venkatesh.m@nec.edu.in',
    condition: 'Good',
    status: 'In Use',
    purchaseDate: '2023-08-20',
    cost: 320000,
    supplier: 'Fortinet Networks India',
    warranty: '3 Years FortiCare (Till Aug 2026)',
    quantity: 2,
    description: 'Hardware accelerated UTM firewall with intrusion prevention, SSL deep packet inspection, and 10Gbps throughput.',
  },
  {
    id: 'AST-068',
    name: 'Ubiquiti UniFi 6 Enterprise Tri-Band Ceiling Mount WiFi 6 AP',
    mainCategory: 'Teaching Equipment',
    category: 'Camera & AV',
    itemType: 'WiFi Access Point',
    building: 'IT Block',
    department: 'IT',
    room: 'IT-101',
    assignedTo: 'Prof. Ramesh Nair',
    assignedRole: 'Network In-Charge',
    assignedEmail: 'ramesh.nair@nec.edu.in',
    condition: 'Good',
    status: 'In Use',
    purchaseDate: '2024-02-10',
    cost: 28500,
    supplier: 'Ubiquiti Enterprise',
    warranty: '2 Years (Till Feb 2026)',
    quantity: 8,
    description: 'High-density 10.2 Gbps aggregate throughput tri-band WiFi 6 access points with 2.5GbE PoE+ uplink ports.',
  },
  {
    id: 'AST-069',
    name: 'BenQ 4000 Lumens Full HD Wireless Smart Projector',
    mainCategory: 'Teaching Equipment',
    category: 'Projector',
    itemType: 'Smart Projector',
    building: 'IT Block',
    department: 'IT',
    room: 'IT-101',
    assignedTo: 'Dr. M. Venkatesh',
    assignedRole: 'Smart Classroom Head',
    assignedEmail: 'venkatesh.m@nec.edu.in',
    condition: 'Good',
    status: 'In Use',
    purchaseDate: '2023-09-05',
    cost: 54000,
    supplier: 'BenQ India Pvt Ltd',
    warranty: '3 Years (Till Sep 2026)',
    quantity: 2,
    description: 'Full HD 1080p high brightness smart lecture hall projector with integrated Android wireless presentation capabilities.',
  },
  {
    id: 'AST-070',
    name: 'Lenovo ThinkPad T14 Gen 4 Intel Core i7 Faculty Laptops',
    mainCategory: 'Teaching Equipment',
    category: 'Camera & AV',
    itemType: 'Faculty Laptop',
    building: 'IT Block',
    department: 'IT',
    room: 'IT-101',
    assignedTo: 'Prof. Ramesh Nair',
    assignedRole: 'Faculty Staff',
    assignedEmail: 'ramesh.nair@nec.edu.in',
    condition: 'Good',
    status: 'In Use',
    purchaseDate: '2024-03-01',
    cost: 95000,
    supplier: 'Lenovo India Enterprise',
    warranty: '3 Years Premier Support (Till Mar 2027)',
    quantity: 12,
    description: 'Mil-spec tested durable lightweight laptops with 32GB RAM, 1TB SSD, fingerprint scanner, and backlit keyboard for faculty.',
  },
  {
    id: 'AST-071',
    name: 'Canon ImageRunner Enterprise Network Multifunction Copier & Scanner',
    mainCategory: 'Teaching Equipment',
    category: 'Camera & AV',
    itemType: 'Network Copier',
    building: 'IT Block',
    department: 'IT',
    room: 'IT-Office',
    assignedTo: 'Dr. M. Venkatesh',
    assignedRole: 'Department Administrator',
    assignedEmail: 'venkatesh.m@nec.edu.in',
    condition: 'Good',
    status: 'In Use',
    purchaseDate: '2023-06-12',
    cost: 135000,
    supplier: 'Canon India Pvt Ltd',
    warranty: '3 Years AMC (Till Jun 2026)',
    quantity: 2,
    description: 'Heavy duty A3 laser multifunction printer with 45ppm speed, automatic duplex document feeder, and network card scanner.',
  },

  // =========================================================================
  // 5. AIDS (AI & Data Science)
  // =========================================================================
  {
    id: 'AST-072',
    name: 'NVIDIA DGX Station A100 AI Supercomputer Workstation',
    mainCategory: 'Teaching Equipment',
    category: 'Camera & AV',
    itemType: 'AI Supercomputer',
    building: 'Engineering Block',
    department: 'AIDS',
    room: 'AIDS-Lab1',
    assignedTo: 'Dr. Nalini Patel',
    assignedRole: 'Head of AIDS Department',
    assignedEmail: 'nalini.patel@nec.edu.in',
    condition: 'Good',
    status: 'In Use',
    purchaseDate: '2024-01-20',
    cost: 1850000,
    supplier: 'NVIDIA Enterprise India',
    warranty: '3 Years Enterprise ProSupport (Till Jan 2027)',
    quantity: 1,
    description: '4x NVIDIA A100 80GB GPUs with 320GB total GPU VRAM, 512GB system RAM, liquid cooled for foundational LLM and vision model training.',
  },
  {
    id: 'AST-073',
    name: 'HP Z4 G5 Workstation Intel Xeon 64GB RAM with RTX 4080 GPU',
    mainCategory: 'Teaching Equipment',
    category: 'Camera & AV',
    itemType: 'AI Workstation',
    building: 'Engineering Block',
    department: 'AIDS',
    room: 'AIDS-Lab1',
    assignedTo: 'Prof. Suresh Babu',
    assignedRole: 'Deep Learning Lab Head',
    assignedEmail: 'suresh.babu@nec.edu.in',
    condition: 'Good',
    status: 'In Use',
    purchaseDate: '2024-02-15',
    cost: 215000,
    supplier: 'HP Enterprise India',
    warranty: '3 Years Onsite (Till Feb 2027)',
    quantity: 25,
    description: 'Intel Xeon W-2400 processor workstations with 64GB ECC RAM, 2TB Gen4 SSD, and RTX 4080 16GB GPU for AI laboratory coursework.',
  },
  {
    id: 'AST-074',
    name: 'LG 34" 21:9 UltraWide Curved Multi-Window Data Analytics Monitors',
    mainCategory: 'Teaching Equipment',
    category: 'Camera & AV',
    itemType: 'LED Monitor',
    building: 'Engineering Block',
    department: 'AIDS',
    room: 'AIDS-Lab1',
    assignedTo: 'Prof. Suresh Babu',
    assignedRole: 'Data Visualization Lab Head',
    assignedEmail: 'suresh.babu@nec.edu.in',
    condition: 'Good',
    status: 'In Use',
    purchaseDate: '2024-02-18',
    cost: 34000,
    supplier: 'LG Electronics India',
    warranty: '3 Years (Till Feb 2027)',
    quantity: 25,
    description: '34-inch WQHD 3440x1440 curved IPS panels with dual controller and split screen software for real-time model telemetry.',
  },
  {
    id: 'AST-075',
    name: 'Interactive 86" 4K Smart Board Display with Dual Android & OPS Windows',
    mainCategory: 'Teaching Equipment',
    category: 'Boards',
    itemType: 'Interactive Smart Board',
    building: 'Engineering Block',
    department: 'AIDS',
    room: 'AIDS-101',
    assignedTo: 'Dr. Nalini Patel',
    assignedRole: 'Smart Classroom Supervisor',
    assignedEmail: 'nalini.patel@nec.edu.in',
    condition: 'Good',
    status: 'In Use',
    purchaseDate: '2024-03-10',
    cost: 168000,
    supplier: 'ViewSonic Corporation',
    warranty: '3 Years Comprehensive (Till Mar 2027)',
    quantity: 2,
    description: '86-inch anti-glare toughened 4K display with 40-point touch, wireless screen mirroring and built-in conference camera array.',
  },
  {
    id: 'AST-076',
    name: 'APC 15kVA Online Double-Conversion Clean Power Backup UPS',
    mainCategory: 'Electricals',
    category: 'Fans & Cooling',
    itemType: 'Online UPS',
    building: 'Engineering Block',
    department: 'AIDS',
    room: 'AIDS-Lab1',
    assignedTo: 'Prof. Suresh Babu',
    assignedRole: 'Power Infrastructure In-Charge',
    assignedEmail: 'suresh.babu@nec.edu.in',
    condition: 'Good',
    status: 'In Use',
    purchaseDate: '2024-01-25',
    cost: 285000,
    supplier: 'Schneider Electric',
    warranty: '3 Years (Till Jan 2027)',
    quantity: 2,
    description: 'Pure sine wave 3-phase to 1-phase double-conversion online UPS with external tubular battery racks for AI training clusters.',
  },
  {
    id: 'AST-077',
    name: 'Apple MacBook Pro 16" M3 Max Data Science Faculty Laptops',
    mainCategory: 'Teaching Equipment',
    category: 'Camera & AV',
    itemType: 'Faculty Laptop',
    building: 'Engineering Block',
    department: 'AIDS',
    room: 'AIDS-101',
    assignedTo: 'Dr. Nalini Patel',
    assignedRole: 'Faculty Staff',
    assignedEmail: 'nalini.patel@nec.edu.in',
    condition: 'Good',
    status: 'In Use',
    purchaseDate: '2024-04-05',
    cost: 299000,
    supplier: 'Apple India Pvt Ltd',
    warranty: '3 Years AppleCare+ (Till Apr 2027)',
    quantity: 6,
    description: '16-inch Liquid Retina XDR laptops with 16-core CPU, 40-core GPU, 48GB unified memory, and 1TB SSD for advanced algorithmic research.',
  },

  // =========================================================================
  // 6. ECE
  // =========================================================================
  {
    id: 'AST-009',
    name: 'Executive Teak Wood Faculty Work Desk',
    mainCategory: 'Furniture',
    category: 'Table',
    itemType: 'Faculty Table',
    building: 'Engineering Block',
    department: 'ECE',
    room: 'ECE-Lab2',
    assignedTo: 'Prof. Ramesh Nair',
    assignedRole: 'ECE Dept In-Charge',
    assignedEmail: 'ramesh.nair@nec.edu.in',
    condition: 'Good',
    status: 'In Use',
    purchaseDate: '2022-09-18',
    cost: 16500,
    supplier: 'Royaloak Furniture',
    warranty: '3 Years Standard',
    quantity: 4,
    description: '5x3 ft melamine finished faculty desk with 3-drawer side pedestal, central lock, and cable pass-through port.',
  },
  {
    id: 'AST-015',
    name: 'Heavy Duty Metal Tool & Equipment Storage Cabinet',
    mainCategory: 'Furniture',
    category: 'Cupboard & Storage',
    itemType: 'Storage Cabinet',
    building: 'Engineering Block',
    department: 'ECE',
    room: 'ECE-Lab2',
    assignedTo: 'Prof. Ramesh Nair',
    assignedRole: 'Lab Custodian',
    assignedEmail: 'ramesh.nair@nec.edu.in',
    condition: 'Good',
    status: 'In Use',
    purchaseDate: '2023-09-12',
    cost: 11200,
    supplier: 'Methodex Systems',
    warranty: '3 Years (Till Sep 2026)',
    quantity: 6,
    description: 'Reinforced dual-door multi-tier equipment storage cabinet for electronic breadboards and test kits.',
  },
  {
    id: 'AST-030',
    name: 'ViewSonic Portable 3000-Lumens LED Smart Projector',
    mainCategory: 'Teaching Equipment',
    category: 'Projector',
    itemType: 'LED Projector',
    building: 'Engineering Block',
    department: 'ECE',
    room: 'ECE-Lab2',
    assignedTo: 'Prof. Ramesh Nair',
    assignedRole: 'ECE Dept In-Charge',
    assignedEmail: 'ramesh.nair@nec.edu.in',
    condition: 'Good',
    status: 'Available',
    purchaseDate: '2024-03-01',
    cost: 38000,
    supplier: 'ViewSonic',
    warranty: '3 Years (Till Mar 2027)',
    quantity: 2,
    description: 'Compact 3000-lumen LED projector with Harman Kardon speaker and instant power-on for departmental seminars.',
  },
  {
    id: 'AST-078',
    name: 'Tektronix 4-Channel 100MHz Digital Storage Oscilloscopes (DSO)',
    mainCategory: 'Teaching Equipment',
    category: 'Camera & AV',
    itemType: 'Oscilloscope',
    building: 'Engineering Block',
    department: 'ECE',
    room: 'ECE-Lab1',
    assignedTo: 'Prof. Ramesh Nair',
    assignedRole: 'Analog Circuits Lab Head',
    assignedEmail: 'ramesh.nair@nec.edu.in',
    condition: 'Good',
    status: 'In Use',
    purchaseDate: '2023-07-15',
    cost: 65000,
    supplier: 'Tektronix India Pvt Ltd',
    warranty: '3 Years (Till Jul 2026)',
    quantity: 15,
    description: '100MHz 4-channel DSO with 1GS/s sampling rate, 7-inch WVGA color display, 32 automated measurements and USB interface.',
  },
  {
    id: 'AST-079',
    name: 'Keysight Multi-Waveform 30MHz Arbitrary Function Generators',
    mainCategory: 'Teaching Equipment',
    category: 'Camera & AV',
    itemType: 'Signal Generator',
    building: 'Engineering Block',
    department: 'ECE',
    room: 'ECE-Lab1',
    assignedTo: 'Prof. Ramesh Nair',
    assignedRole: 'Circuits Lab Supervisor',
    assignedEmail: 'ramesh.nair@nec.edu.in',
    condition: 'Good',
    status: 'In Use',
    purchaseDate: '2023-08-12',
    cost: 48000,
    supplier: 'Keysight Technologies',
    warranty: '3 Years (Till Aug 2026)',
    quantity: 15,
    description: 'Dual channel 30MHz true point-by-point arbitrary waveform generator with sine, square, ramp, pulse, and noise modulation capabilities.',
  },
  {
    id: 'AST-080',
    name: 'Xilinx Spartan-7 FPGA Digital Logic Trainer Kit with JTAG Programmers',
    mainCategory: 'Teaching Equipment',
    category: 'Camera & AV',
    itemType: 'FPGA Development Kit',
    building: 'Engineering Block',
    department: 'ECE',
    room: 'ECE-Lab2',
    assignedTo: 'Dr. K. Swaminathan',
    assignedRole: 'VLSI & Embedded Lab Head',
    assignedEmail: 'swaminathan.k@nec.edu.in',
    condition: 'Good',
    status: 'In Use',
    purchaseDate: '2023-10-25',
    cost: 32000,
    supplier: 'Digilent / CoreEL Technologies',
    warranty: '2 Years (Till Oct 2025)',
    quantity: 20,
    description: 'FPGA development boards with on-board USB-JTAG, PMOD expansion headers, 7-segment displays, LEDs, switches, and Vivado design license.',
  },
  {
    id: 'AST-081',
    name: 'Rohde & Schwarz 3GHz Spectrum Analyzer with RF Near-Field Probes',
    mainCategory: 'Teaching Equipment',
    category: 'Camera & AV',
    itemType: 'Spectrum Analyzer',
    building: 'Engineering Block',
    department: 'ECE',
    room: 'ECE-Lab2',
    assignedTo: 'Dr. K. Swaminathan',
    assignedRole: 'RF & Microwave Head',
    assignedEmail: 'swaminathan.k@nec.edu.in',
    condition: 'Good',
    status: 'In Use',
    purchaseDate: '2023-12-05',
    cost: 460000,
    supplier: 'Rohde & Schwarz India',
    warranty: '3 Years (Till Dec 2026)',
    quantity: 2,
    description: '5kHz to 3GHz high dynamic range spectrum analyzer with tracking generator and EMC pre-compliance test probe set.',
  },
  {
    id: 'AST-082',
    name: 'Hakko ESD-Safe Digital Soldering and Desoldering Rework Station',
    mainCategory: 'Teaching Equipment',
    category: 'Camera & AV',
    itemType: 'Soldering Station',
    building: 'Engineering Block',
    department: 'ECE',
    room: 'ECE-Lab1',
    assignedTo: 'Prof. Ramesh Nair',
    assignedRole: 'Hardware Prototyping Head',
    assignedEmail: 'ramesh.nair@nec.edu.in',
    condition: 'Good',
    status: 'In Use',
    purchaseDate: '2023-04-10',
    cost: 22000,
    supplier: 'Hakko Corporation India',
    warranty: '2 Years Standard',
    quantity: 10,
    description: 'Microprocessor temperature controlled lead-free ESD soldering station with vacuum desoldering gun and digital thermal calibration.',
  },

  // =========================================================================
  // 7. EEE (Electrical & Electronics)
  // =========================================================================
  {
    id: 'AST-083',
    name: '3-Phase 5HP AC Induction Motor Dynamo Coupled Electrical Test Bench',
    mainCategory: 'Teaching Equipment',
    category: 'Camera & AV',
    itemType: 'Electrical Machine Bench',
    building: 'Engineering Block',
    department: 'EEE',
    room: 'EEE-MachinesLab',
    assignedTo: 'Dr. R. Vijay Anand',
    assignedRole: 'Head of Department - EEE',
    assignedEmail: 'vijayanand.r@nec.edu.in',
    condition: 'Good',
    status: 'In Use',
    purchaseDate: '2023-03-20',
    cost: 145000,
    supplier: 'Kirloskar Electric Co',
    warranty: '3 Years (Till Mar 2026)',
    quantity: 6,
    description: '3-phase 415V 5HP squirrel cage induction motor coupled with eddy current dynamometer, digital torque indicator and tachometer.',
  },
  {
    id: 'AST-084',
    name: 'Heavy Duty Double-Field Shunt DC Motor Generator Test Set',
    mainCategory: 'Teaching Equipment',
    category: 'Camera & AV',
    itemType: 'DC Motor Generator',
    building: 'Engineering Block',
    department: 'EEE',
    room: 'EEE-MachinesLab',
    assignedTo: 'Prof. Karthik Rajan',
    assignedRole: 'Machines Lab Supervisor',
    assignedEmail: 'karthik.rajan@nec.edu.in',
    condition: 'Good',
    status: 'In Use',
    purchaseDate: '2022-11-18',
    cost: 125000,
    supplier: 'Benn Electricals',
    warranty: '3 Years Standard',
    quantity: 4,
    description: '220V 3HP DC shunt motor coupled to separately excited DC generator on heavy vibration-isolated bedplate with resistive lamp load bank.',
  },
  {
    id: 'AST-085',
    name: 'Yokogawa Precision Digital Power Meter & Power Factor Analyzer',
    mainCategory: 'Teaching Equipment',
    category: 'Camera & AV',
    itemType: 'Power Meter',
    building: 'Engineering Block',
    department: 'EEE',
    room: 'EEE-PowerLab',
    assignedTo: 'Dr. R. Vijay Anand',
    assignedRole: 'Power Systems Head',
    assignedEmail: 'vijayanand.r@nec.edu.in',
    condition: 'Good',
    status: 'In Use',
    purchaseDate: '2023-09-14',
    cost: 88000,
    supplier: 'Yokogawa India Ltd',
    warranty: '3 Years (Till Sep 2026)',
    quantity: 8,
    description: 'High precision 0.1% accuracy digital power analyzer measuring active, reactive, apparent power, harmonics, and total power factor.',
  },
  {
    id: 'AST-086',
    name: 'Automatic Single-Phase & Three-Phase Auto-Transformer Variacs 15A',
    mainCategory: 'Electricals',
    category: 'Fans & Cooling',
    itemType: 'Variac Transformer',
    building: 'Engineering Block',
    department: 'EEE',
    room: 'EEE-PowerLab',
    assignedTo: 'Prof. Karthik Rajan',
    assignedRole: 'Power Lab Technician',
    assignedEmail: 'karthik.rajan@nec.edu.in',
    condition: 'Good',
    status: 'In Use',
    purchaseDate: '2023-06-28',
    cost: 18500,
    supplier: 'Automatic Electric Ltd',
    warranty: '2 Years Standard',
    quantity: 12,
    description: '0-270V 15A variable autotransformers with silver alloy contacts and analog volt/ammeter indicators in powder-coated steel enclosures.',
  },
  {
    id: 'AST-087',
    name: 'High-Voltage Insulation Breakdown Tester and Megohmmeter (5kV)',
    mainCategory: 'Teaching Equipment',
    category: 'Camera & AV',
    itemType: 'Insulation Tester',
    building: 'Engineering Block',
    department: 'EEE',
    room: 'EEE-HighVoltageLab',
    assignedTo: 'Dr. R. Vijay Anand',
    assignedRole: 'High Voltage Lab Head',
    assignedEmail: 'vijayanand.r@nec.edu.in',
    condition: 'Good',
    status: 'In Use',
    purchaseDate: '2023-10-08',
    cost: 110000,
    supplier: 'Megger India Pvt Ltd',
    warranty: '3 Years (Till Oct 2026)',
    quantity: 3,
    description: '5kV digital insulation resistance tester with polarization index, dielectric absorption ratio, and automated breakdown discharge voltage logging.',
  },
  {
    id: 'AST-088',
    name: 'Siemens PLC & SCADA Industrial Automation Training System Console',
    mainCategory: 'Teaching Equipment',
    category: 'Camera & AV',
    itemType: 'PLC Training Console',
    building: 'Engineering Block',
    department: 'EEE',
    room: 'EEE-ControlLab',
    assignedTo: 'Prof. Karthik Rajan',
    assignedRole: 'Control Systems Lab Head',
    assignedEmail: 'karthik.rajan@nec.edu.in',
    condition: 'Good',
    status: 'In Use',
    purchaseDate: '2024-01-18',
    cost: 260000,
    supplier: 'Siemens Industrial Solutions',
    warranty: '3 Years (Till Jan 2027)',
    quantity: 4,
    description: 'Siemens S7-1200 PLC trainer bench with 7-inch KTP700 color HMI touch panel, analog I/O modules, stepper motor rig and TIA Portal suite.',
  },
  {
    id: 'AST-089',
    name: 'Fluke True-RMS Industrial Digital Multimeter with Temperature Probe',
    mainCategory: 'Teaching Equipment',
    category: 'Camera & AV',
    itemType: 'Digital Multimeter',
    building: 'Engineering Block',
    department: 'EEE',
    room: 'EEE-PowerLab',
    assignedTo: 'Prof. Karthik Rajan',
    assignedRole: 'Instrumentation In-Charge',
    assignedEmail: 'karthik.rajan@nec.edu.in',
    condition: 'Good',
    status: 'In Use',
    purchaseDate: '2023-05-12',
    cost: 19500,
    supplier: 'Fluke Corporation India',
    warranty: 'Lifetime Limited Hardware',
    quantity: 16,
    description: 'CAT IV 600V safety rated rugged industrial digital multimeters with built-in thermocouple thermometer and magnetic hanging strap.',
  },

  // =========================================================================
  // 8. SCIENCE & HUMANITIES
  // =========================================================================
  {
    id: 'AST-005',
    name: 'Chrome Sled-Base Cushioned Visitor Chair',
    mainCategory: 'Furniture',
    category: 'Chair',
    itemType: 'Visitor Chair',
    building: 'Science Block',
    department: 'Science & Humanities',
    room: 'SH-PhysicsLab',
    assignedTo: 'Prof. Dinesh Kumar',
    assignedRole: 'Head of Department',
    assignedEmail: 'dinesh.kumar@nec.edu.in',
    condition: 'Good',
    status: 'Available',
    purchaseDate: '2023-11-04',
    cost: 1850,
    supplier: 'Methodex Systems',
    warranty: '2 Years (Till Nov 2025)',
    quantity: 16,
    description: 'Sled base anti-tip chrome finished visitor chairs with high-density anti-sag foam cushioning for faculty offices.',
  },
  {
    id: 'AST-007',
    name: 'Granite Top 3-Person Student Chemistry Lab Table',
    mainCategory: 'Furniture',
    category: 'Table',
    itemType: 'Student Table',
    building: 'Science Block',
    department: 'Science & Humanities',
    room: 'SH-ChemistryLab',
    assignedTo: 'Dr. Lalitha Devi',
    assignedRole: 'Chemistry Lab Supervisor',
    assignedEmail: 'lalitha.devi@nec.edu.in',
    condition: 'Fair',
    status: 'In Use',
    purchaseDate: '2021-10-12',
    cost: 7800,
    supplier: 'National Furnishers',
    warranty: '2 Years Standard',
    quantity: 12,
    description: 'Chemical and acid-resistant jet black granite top laboratory student work table with reagent shelves.',
  },
  {
    id: 'AST-011',
    name: 'Modular Library Reading & Study Table (6-Seater)',
    mainCategory: 'Furniture',
    category: 'Table',
    itemType: 'Student Table',
    building: 'Science Block',
    department: 'Science & Humanities',
    room: 'SH-Library',
    assignedTo: 'Ms. Geeta Nair',
    assignedRole: 'Chief Librarian',
    assignedEmail: 'geeta.nair@nec.edu.in',
    condition: 'Good',
    status: 'In Use',
    purchaseDate: '2023-03-20',
    cost: 14200,
    supplier: 'Methodex Systems',
    warranty: '3 Years (Till Mar 2026)',
    quantity: 18,
    description: 'Heavy-duty 6-seater library study tables with frosted acrylic privacy dividers and built-in USB charging ports.',
  },
  {
    id: 'AST-013',
    name: 'Teak Wood Display Cupboard with Toughened Glass Doors',
    mainCategory: 'Furniture',
    category: 'Cupboard & Storage',
    itemType: 'Wooden Cupboard',
    building: 'Science Block',
    department: 'Science & Humanities',
    room: 'SH-PhysicsLab',
    assignedTo: 'Prof. Dinesh Kumar',
    assignedRole: 'Dept Head',
    assignedEmail: 'dinesh.kumar@nec.edu.in',
    condition: 'Good',
    status: 'In Use',
    purchaseDate: '2023-01-20',
    cost: 19500,
    supplier: 'Durian Furniture',
    warranty: '3 Years (Till Jan 2026)',
    quantity: 3,
    description: 'Toughened glass door specimen and delicate optical instrument display cupboard with lockable bottom drawers.',
  },
  {
    id: 'AST-016',
    name: 'Double-Sided Heavy Steel Library Book Rack Stack',
    mainCategory: 'Furniture',
    category: 'Cupboard & Storage',
    itemType: 'Book Rack',
    building: 'Science Block',
    department: 'Science & Humanities',
    room: 'SH-Library',
    assignedTo: 'Ms. Geeta Nair',
    assignedRole: 'Chief Librarian',
    assignedEmail: 'geeta.nair@nec.edu.in',
    condition: 'Good',
    status: 'In Use',
    purchaseDate: '2022-04-10',
    cost: 18500,
    supplier: 'Methodex Systems',
    warranty: '5 Years (Till Apr 2027)',
    quantity: 24,
    description: 'Modular 5-tier double-faced steel book stack unit with acrylic label holders and book stop partitions.',
  },
  {
    id: 'AST-022',
    name: 'Double-Sided Mobile Rolling Notice Board with Wheels',
    mainCategory: 'Furniture',
    category: 'Other Furniture',
    itemType: 'Notice Board',
    building: 'Science Block',
    department: 'Science & Humanities',
    room: 'SH-Library',
    assignedTo: 'Ms. Geeta Nair',
    assignedRole: 'Library Coordinator',
    assignedEmail: 'geeta.nair@nec.edu.in',
    condition: 'Good',
    status: 'In Use',
    purchaseDate: '2023-11-12',
    cost: 4900,
    supplier: 'Whitemark Boards',
    warranty: '2 Years (Till Nov 2025)',
    quantity: 3,
    description: 'Castor-mounted double-sided fabric bulletin display board for campus announcements and newsletters.',
  },
  {
    id: 'AST-024',
    name: 'AverMedia 1080p 60FPS Broadcaster Webcam with Tripod',
    mainCategory: 'Teaching Equipment',
    category: 'Camera & AV',
    itemType: 'Web cam',
    building: 'Science Block',
    department: 'Science & Humanities',
    room: 'SH-SmartClass',
    assignedTo: 'Prof. Dinesh Kumar',
    assignedRole: 'Smart Classroom Supervisor',
    assignedEmail: 'dinesh.kumar@nec.edu.in',
    condition: 'Good',
    status: 'In Use',
    purchaseDate: '2023-10-15',
    cost: 9500,
    supplier: 'AverMedia Technologies',
    warranty: '2 Years (Till Oct 2025)',
    quantity: 3,
    description: 'Full HD wide-angle broadcast web camera with omnidirectional stereo mic and flexible desktop tripod stand.',
  },
  {
    id: 'AST-027',
    name: 'Interactive 75" 4K UHD Multi-Touch Smart Display Board',
    mainCategory: 'Teaching Equipment',
    category: 'Boards',
    itemType: 'Interactive Smart Board',
    building: 'Science Block',
    department: 'Science & Humanities',
    room: 'SH-SmartClass',
    assignedTo: 'Prof. Dinesh Kumar',
    assignedRole: 'Smart Classroom Supervisor',
    assignedEmail: 'dinesh.kumar@nec.edu.in',
    condition: 'Good',
    status: 'In Use',
    purchaseDate: '2024-06-10',
    cost: 145000,
    supplier: 'ViewSonic / BenQ',
    warranty: '3 Years Comprehensive (Till Jun 2027)',
    quantity: 2,
    description: '20-point touch capacitive smart board with dual OS (Android 13 + Windows OPS PC module) and wireless screen sharing.',
  },
  {
    id: 'AST-032',
    name: 'Optoma High-Contrast Short-Throw Laser Projector',
    mainCategory: 'Teaching Equipment',
    category: 'Projector',
    itemType: 'Laser Projector',
    building: 'Science Block',
    department: 'Science & Humanities',
    room: 'SH-SmartClass',
    assignedTo: 'Prof. Dinesh Kumar',
    assignedRole: 'Smart Classroom Supervisor',
    assignedEmail: 'dinesh.kumar@nec.edu.in',
    condition: 'Damaged',
    status: 'Needs Inspection',
    purchaseDate: '2023-12-05',
    cost: 110000,
    supplier: 'Optoma Technology',
    warranty: '3 Years (Till Dec 2026)',
    quantity: 1,
    description: 'Short throw laser projector paired with interactive whiteboard to eliminate presenter shadows.',
  },
  {
    id: 'AST-041',
    name: 'Philips 36W Recessed Square LED Panel Light (2x2 ft)',
    mainCategory: 'Electricals',
    category: 'Lighting',
    itemType: 'LED Light',
    building: 'Science Block',
    department: 'Science & Humanities',
    room: 'SH-Library',
    assignedTo: 'Ms. Geeta Nair',
    assignedRole: 'Librarian In-Charge',
    assignedEmail: 'geeta.nair@nec.edu.in',
    condition: 'Good',
    status: 'In Use',
    purchaseDate: '2024-01-10',
    cost: 1600,
    supplier: 'Signify / Philips Lighting',
    warranty: '2 Years (Till Jan 2026)',
    quantity: 32,
    description: 'Cool white 6500K flicker-free eye-comfort LED grid panel for reading hall glare-free illumination.',
  },
  {
    id: 'AST-090',
    name: 'Olympus Binocular Compound High-Resolution Optical Microscope',
    mainCategory: 'Teaching Equipment',
    category: 'Camera & AV',
    itemType: 'Optical Microscope',
    building: 'Science Block',
    department: 'Science & Humanities',
    room: 'SH-PhysicsLab',
    assignedTo: 'Prof. Dinesh Kumar',
    assignedRole: 'Optics Lab Supervisor',
    assignedEmail: 'dinesh.kumar@nec.edu.in',
    condition: 'Good',
    status: 'In Use',
    purchaseDate: '2023-08-25',
    cost: 32000,
    supplier: 'Olympus Opto Systems',
    warranty: '3 Years (Till Aug 2026)',
    quantity: 20,
    description: 'Binocular biological microscope with quadruple revolving nosepiece, plan achromat 4x, 10x, 40x, 100x oil immersion objectives and LED illuminator.',
  },
  {
    id: 'AST-091',
    name: 'Digital Precision Electronic Analytical Laboratory Balance 0.1mg',
    mainCategory: 'Teaching Equipment',
    category: 'Camera & AV',
    itemType: 'Analytical Balance',
    building: 'Science Block',
    department: 'Science & Humanities',
    room: 'SH-ChemistryLab',
    assignedTo: 'Dr. Lalitha Devi',
    assignedRole: 'Chemistry Lab Supervisor',
    assignedEmail: 'lalitha.devi@nec.edu.in',
    condition: 'Good',
    status: 'In Use',
    purchaseDate: '2023-09-18',
    cost: 42000,
    supplier: 'Mettler Toledo India',
    warranty: '3 Years (Till Sep 2026)',
    quantity: 4,
    description: 'High precision 0.1mg internal calibration analytical balance with glass draft shield and backlit LCD display.',
  },

  // =========================================================================
  // 9. ADMIN BLOCK
  // =========================================================================
  {
    id: 'AST-092',
    name: 'Executive High-Back Leatherette Director & Officer Chair',
    mainCategory: 'Furniture',
    category: 'Chair',
    itemType: 'Faculty Chair',
    building: 'Admin Block',
    department: 'Admin Block',
    room: 'ADM-101',
    assignedTo: 'Dr. Rajesh Kumar',
    assignedRole: 'Campus Director & Super Admin',
    assignedEmail: 'rajesh.kumar@nec.edu.in',
    condition: 'Good',
    status: 'In Use',
    purchaseDate: '2024-01-15',
    cost: 14500,
    supplier: 'Durian Furniture Commercial',
    warranty: '5 Years (Till Jan 2029)',
    quantity: 8,
    description: 'Premium ergonomic executive high-back swivel chairs with multi-position synchro tilt lock, lumbar contouring, and padded armrests.',
  },
  {
    id: 'AST-093',
    name: 'Boat-Shaped 12-Seater Boardroom Conference Table with Cable Modules',
    mainCategory: 'Furniture',
    category: 'Table',
    itemType: 'Office Table',
    building: 'Admin Block',
    department: 'Admin Block',
    room: 'ADM-Hall',
    assignedTo: 'Dr. Rajesh Kumar',
    assignedRole: 'Board of Governors In-Charge',
    assignedEmail: 'rajesh.kumar@nec.edu.in',
    condition: 'Good',
    status: 'In Use',
    purchaseDate: '2024-02-10',
    cost: 52000,
    supplier: 'Featherlite Seating Ltd',
    warranty: '5 Years (Till Feb 2029)',
    quantity: 2,
    description: 'Heavy duty executive boat-shaped boardroom conference table with pop-up motorized HDMI, RJ45 and power socket modules.',
  },
  {
    id: 'AST-094',
    name: 'Dell OptiPlex 7010 Micro Intel Core i7 Administrative Desktop PCs',
    mainCategory: 'Teaching Equipment',
    category: 'Camera & AV',
    itemType: 'Desktop PC',
    building: 'Admin Block',
    department: 'Admin Block',
    room: 'ADM-101',
    assignedTo: 'Ms. Priya Mehta',
    assignedRole: 'Estate Officer & Records Custodian',
    assignedEmail: 'priya.mehta@nec.edu.in',
    condition: 'Good',
    status: 'In Use',
    purchaseDate: '2024-02-18',
    cost: 58000,
    supplier: 'Dell India Enterprise',
    warranty: '3 Years ProSupport (Till Feb 2027)',
    quantity: 15,
    description: 'Micro form-factor desktop PCs with Intel Core i7 13th Gen, 16GB DDR5 RAM, 512GB NVMe SSD, and 24-inch Dell FHD IPS monitors.',
  },
  {
    id: 'AST-095',
    name: 'HP EliteBook 840 G10 Intel Core i7 Executive Staff Laptops',
    mainCategory: 'Teaching Equipment',
    category: 'Camera & AV',
    itemType: 'Faculty Laptop',
    building: 'Admin Block',
    department: 'Admin Block',
    room: 'ADM-101',
    assignedTo: 'Dr. Rajesh Kumar',
    assignedRole: 'Executive Administration',
    assignedEmail: 'rajesh.kumar@nec.edu.in',
    condition: 'Good',
    status: 'In Use',
    purchaseDate: '2024-03-05',
    cost: 105000,
    supplier: 'HP Enterprise India',
    warranty: '3 Years Onsite (Till Mar 2027)',
    quantity: 8,
    description: 'Lightweight magnesium chassis executive enterprise laptops with Intel Core i7, 32GB RAM, 1TB NVMe SSD, and LTE SIM connectivity.',
  },
  {
    id: 'AST-096',
    name: 'Kyocera TASKalfa 4012i Heavy Duty Central Network Laser Copier',
    mainCategory: 'Teaching Equipment',
    category: 'Camera & AV',
    itemType: 'Network Copier',
    building: 'Admin Block',
    department: 'Admin Block',
    room: 'ADM-Records',
    assignedTo: 'Ms. Priya Mehta',
    assignedRole: 'Records Officer',
    assignedEmail: 'priya.mehta@nec.edu.in',
    condition: 'Good',
    status: 'In Use',
    purchaseDate: '2023-08-20',
    cost: 165000,
    supplier: 'Kyocera Document Solutions',
    warranty: '3 Years Full AMC (Till Aug 2026)',
    quantity: 2,
    description: 'A3/A4 commercial multifunction monochrome printer with 40ppm speed, automated 140-sheet dual scan document processor, and secure PIN printing.',
  },
  {
    id: 'AST-097',
    name: 'Godrej Heavy-Duty 4-Drawer Fireproof Record & Document Safe',
    mainCategory: 'Furniture',
    category: 'Cupboard & Storage',
    itemType: 'Filing Cabinet',
    building: 'Admin Block',
    department: 'Admin Block',
    room: 'ADM-Records',
    assignedTo: 'Ms. Priya Mehta',
    assignedRole: 'Estate Officer & Records Custodian',
    assignedEmail: 'priya.mehta@nec.edu.in',
    condition: 'Good',
    status: 'In Use',
    purchaseDate: '2023-04-18',
    cost: 38000,
    supplier: 'Godrej Security Solutions',
    warranty: '5 Years (Till Apr 2028)',
    quantity: 4,
    description: 'UL-tested 2-hour fire rated vertical filing safe cabinet with dual keylock and digital numeric keypad for institutional certificates.',
  },
  {
    id: 'AST-098',
    name: 'Sony 4K Laser Solid-State Boardroom Presentation Projector (6000 Lumens)',
    mainCategory: 'Teaching Equipment',
    category: 'Projector',
    itemType: 'Laser Projector',
    building: 'Admin Block',
    department: 'Admin Block',
    room: 'ADM-Hall',
    assignedTo: 'Dr. Rajesh Kumar',
    assignedRole: 'Conference Hall Custodian',
    assignedEmail: 'rajesh.kumar@nec.edu.in',
    condition: 'Good',
    status: 'In Use',
    purchaseDate: '2024-04-12',
    cost: 195000,
    supplier: 'Sony Professional Solutions',
    warranty: '5 Years (Till Apr 2029)',
    quantity: 1,
    description: 'Z-Phosphor laser light source 20,000-hour maintenance-free projector with motorized lens shift, 4K resolution upscaling, and Crestron control.',
  },
  {
    id: 'AST-099',
    name: 'Cisco Meraki MX85 Enterprise Cloud-Managed Security Gateway & Core Switch',
    mainCategory: 'Teaching Equipment',
    category: 'Camera & AV',
    itemType: 'Network Switch',
    building: 'Admin Block',
    department: 'Admin Block',
    room: 'ADM-ServerRoom',
    assignedTo: 'Mr. Ravi Shankar',
    assignedRole: 'Campus Infrastructure Auditor',
    assignedEmail: 'ravi.shankar@nec.edu.in',
    condition: 'Good',
    status: 'In Use',
    purchaseDate: '2023-09-15',
    cost: 185000,
    supplier: 'Cisco Systems India',
    warranty: 'Lifetime Limited Hardware',
    quantity: 2,
    description: '1Gbps stateful firewall throughput cloud-managed security appliance with dual SFP+ 10GbE uplinks and automated failover routing.',
  },
  {
    id: 'AST-100',
    name: 'Sennheiser SpeechLine Digital Wireless Conference Microphone Kit',
    mainCategory: 'Teaching Equipment',
    category: 'Microphone',
    itemType: 'Wireless Microphone',
    building: 'Admin Block',
    department: 'Admin Block',
    room: 'ADM-Hall',
    assignedTo: 'Mr. Ravi Shankar',
    assignedRole: 'Auditorium AV Tech',
    assignedEmail: 'ravi.shankar@nec.edu.in',
    condition: 'Good',
    status: 'In Use',
    purchaseDate: '2023-11-20',
    cost: 28500,
    supplier: 'Sennheiser Electronics',
    warranty: '2 Years (Till Nov 2025)',
    quantity: 4,
    description: '1.9GHz auto-frequency management wireless handheld & boundary tabletop conference microphones with 256-bit AES audio encryption.',
  },
  {
    id: 'AST-101',
    name: 'Voltas 2.0 Ton Commercial Inverter Cassette Air Conditioners',
    mainCategory: 'Electricals',
    category: 'Fans & Cooling',
    itemType: 'Split AC',
    building: 'Admin Block',
    department: 'Admin Block',
    room: 'ADM-Hall',
    assignedTo: 'Dr. Rajesh Kumar',
    assignedRole: 'Facility Custodian',
    assignedEmail: 'rajesh.kumar@nec.edu.in',
    condition: 'Good',
    status: 'In Use',
    purchaseDate: '2024-03-05',
    cost: 68000,
    supplier: 'Voltas Ltd',
    warranty: '5 Years (Till Mar 2029)',
    quantity: 4,
    description: 'Ceiling mounted 360-degree round flow inverter cassette AC with whisper-quiet operation across the main administrative council hall.',
  }
];

const ASSET_CATALOG_VERSION = 'v8_strict_9_departments_all_86_assets_no_nulls';

const getInitialFurniture = () => {
  if (typeof window === 'undefined' || typeof localStorage === 'undefined') {
    return initialAssets;
  }
  const version = localStorage.getItem('furniture_version');
  const saved = localStorage.getItem('furniture_list');
  if (saved && version === ASSET_CATALOG_VERSION) {
    try {
      const parsed = JSON.parse(saved);
      if (Array.isArray(parsed) && parsed.length >= initialAssets.length) {
        // Ensure every asset in stored list strictly conforms to the 9 allowed departments and has no nulls
        return parsed.map(asset => ({
          ...asset,
          department: mapLegacyDepartment(asset.department),
          description: asset.description || 'General Institutional Asset',
          assignedTo: asset.assignedTo || 'Unassigned',
          assignedRole: asset.assignedRole || 'Staff',
          assignedEmail: asset.assignedEmail || 'admin@nec.edu.in',
          supplier: asset.supplier || 'Campus Procurement',
          warranty: asset.warranty || '1 Year Standard',
          room: asset.room || 'General',
          building: asset.building || 'Engineering Block',
          cost: typeof asset.cost === 'number' ? asset.cost : 0,
          quantity: typeof asset.quantity === 'number' ? asset.quantity : 1,
        }));
      }
    } catch {
      // ignore
    }
  }
  localStorage.setItem('furniture_version', ASSET_CATALOG_VERSION);
  localStorage.setItem('furniture_list', JSON.stringify(initialAssets));
  return initialAssets;
};

const furnitureSlice = createSlice({
  name: 'furniture',
  initialState: {
    list: getInitialFurniture(),
    loading: false,
    error: null,
  },
  reducers: {
    setFurnitureList: (state, action) => {
      state.list = (action.payload || []).map(item => ({
        ...item,
        department: mapLegacyDepartment(item.department),
      }));
      localStorage.setItem('furniture_list', JSON.stringify(state.list));
    },
    addFurniture: (state, action) => {
      const payload = { 
        ...action.payload,
        department: mapLegacyDepartment(action.payload?.department),
        description: action.payload?.description || 'No description provided',
        assignedTo: action.payload?.assignedTo || 'Unassigned',
        assignedRole: action.payload?.assignedRole || 'General Staff',
        assignedEmail: action.payload?.assignedEmail || 'admin@nec.edu.in',
        supplier: action.payload?.supplier || 'Campus Procurement',
        warranty: action.payload?.warranty || 'Standard Warranty',
        room: action.payload?.room || 'General',
        building: action.payload?.building || 'Campus Block',
        cost: typeof action.payload?.cost === 'number' ? action.payload.cost : parseFloat(action.payload?.cost || '0') || 0,
        quantity: typeof action.payload?.quantity === 'number' ? action.payload.quantity : parseInt(action.payload?.quantity || '1', 10) || 1,
      };
      const exists = state.list.some(f => f.id === payload.id);
      if (!exists) {
        state.list.unshift(payload);
      } else {
        const idx = state.list.findIndex(f => f.id === payload.id);
        state.list[idx] = payload;
      }
      localStorage.setItem('furniture_list', JSON.stringify(state.list));
    },
    editFurniture: (state, action) => {
      const idx = state.list.findIndex(f => f.id === action.payload.id);
      if (idx !== -1) {
        state.list[idx] = { 
          ...state.list[idx], 
          ...action.payload,
          department: action.payload?.department ? mapLegacyDepartment(action.payload.department) : state.list[idx].department,
        };
        localStorage.setItem('furniture_list', JSON.stringify(state.list));
      }
    },
    deleteFurniture: (state, action) => {
      state.list = state.list.filter(f => f.id !== action.payload);
      localStorage.setItem('furniture_list', JSON.stringify(state.list));
    },
    updateFurnitureLocation: (state, action) => {
      const item = state.list.find(f => f.id === action.payload.id);
      if (item) {
        if (action.payload.room) item.room = action.payload.room;
        if (action.payload.building) item.building = action.payload.building;
        if (action.payload.department) item.department = mapLegacyDepartment(action.payload.department);
        localStorage.setItem('furniture_list', JSON.stringify(state.list));
      }
    },
    updateFurnitureCustodian: (state, action) => {
      const item = state.list.find(f => f.id === action.payload.id);
      if (item) {
        if (action.payload.assignedTo !== undefined) item.assignedTo = action.payload.assignedTo || 'Unassigned';
        if (action.payload.assignedRole !== undefined) item.assignedRole = action.payload.assignedRole || 'Staff';
        if (action.payload.assignedEmail !== undefined) item.assignedEmail = action.payload.assignedEmail || 'admin@nec.edu.in';
        localStorage.setItem('furniture_list', JSON.stringify(state.list));
      }
    },
    updateFurnitureCondition: (state, action) => {
      const item = state.list.find(f => f.id === action.payload.id);
      if (item) {
        item.condition = action.payload.condition || 'Good';
        localStorage.setItem('furniture_list', JSON.stringify(state.list));
      }
    },
    bulkAssignCustodians: (state, action) => {
      const { assetIds, assignedTo, assignedRole, assignedEmail } = action.payload;
      state.list.forEach((item) => {
        if (assetIds.includes(item.id)) {
          if (assignedTo !== undefined) item.assignedTo = assignedTo || 'Unassigned';
          if (assignedRole !== undefined) item.assignedRole = assignedRole || 'Staff';
          if (assignedEmail !== undefined) item.assignedEmail = assignedEmail || 'admin@nec.edu.in';
        }
      });
      localStorage.setItem('furniture_list', JSON.stringify(state.list));
    },
    resetToDefaultCatalog: (state) => {
      state.list = initialAssets;
      localStorage.setItem('furniture_list', JSON.stringify(initialAssets));
    },
  },
});

export const {
  setFurnitureList,
  addFurniture,
  editFurniture,
  deleteFurniture,
  updateFurnitureLocation,
  updateFurnitureCustodian,
  updateFurnitureCondition,
  bulkAssignCustodians,
  resetToDefaultCatalog,
} = furnitureSlice.actions;

export default furnitureSlice.reducer;
