import { createSlice } from '@reduxjs/toolkit';

const getInitialPurchaseHistory = () => {
  const saved = localStorage.getItem('purchase_history_list');
  if (saved) {
    try {
      const parsed = JSON.parse(saved);
      if (
        Array.isArray(parsed) &&
        parsed.length >= 15 &&
        parsed.some(p => p.categoryName === 'Laboratory') &&
        parsed.some(p => p.categoryName === 'IT Hardware')
      ) {
        return parsed;
      }
    } catch {
      // ignore
    }
  }

  const initial = [
    {
      id: 'PUR-2024-001',
      assetId: 'AST-001',
      assetName: 'Ergonomic High-Back Mesh Task Chair',
      vendorId: 'VND-002',
      vendorName: 'ErgoDesign Workspaces',
      categoryId: 'CAT-001',
      categoryName: 'Furniture',
      subcategoryId: 'SUB-CHR',
      subcategoryName: 'Chair',
      itemType: 'Task Chair',
      purchaseDate: '2024-06-15',
      purchasePrice: 7200.00,
      quantity: 20,
      totalAmount: 144000.00,
      invoiceNumber: 'INV-ED-2024-88',
      invoiceDate: '2024-06-12',
      warrantyExpiry: '2027-06-15 (3 Years)',
      notes: 'Batch procurement for CSE Computing Lab 1.'
    },
    {
      id: 'PUR-2025-002',
      assetId: 'AST-001',
      assetName: 'Ergonomic High-Back Mesh Task Chair',
      vendorId: 'VND-002',
      vendorName: 'ErgoDesign Workspaces',
      categoryId: 'CAT-001',
      categoryName: 'Furniture',
      subcategoryId: 'SUB-CHR',
      subcategoryName: 'Chair',
      itemType: 'Task Chair',
      purchaseDate: '2025-02-10',
      purchasePrice: 7500.00,
      quantity: 15,
      totalAmount: 112500.00,
      invoiceNumber: 'INV-ED-2025-102',
      invoiceDate: '2025-02-08',
      warrantyExpiry: '2028-02-10 (3 Years)',
      notes: 'Replenishment batch for AI Research Lab.'
    },
    {
      id: 'PUR-2026-003',
      assetId: 'AST-001',
      assetName: 'Ergonomic High-Back Mesh Task Chair',
      vendorId: 'VND-002',
      vendorName: 'ErgoDesign Workspaces',
      categoryId: 'CAT-001',
      categoryName: 'Furniture',
      subcategoryId: 'SUB-CHR',
      subcategoryName: 'Chair',
      itemType: 'Task Chair',
      purchaseDate: '2026-01-15',
      purchasePrice: 7800.00,
      quantity: 5,
      totalAmount: 39000.00,
      invoiceNumber: 'INV-ED-2026-019',
      invoiceDate: '2026-01-14',
      warrantyExpiry: '2029-01-15 (3 Years)',
      notes: 'Additional units for HOD meeting room.'
    },
    {
      id: 'PUR-2024-004',
      assetId: 'AST-002',
      assetName: 'Student Chair with Wooden Writing Pad',
      vendorId: 'VND-004',
      vendorName: 'Godrej Interio Commercial',
      categoryId: 'CAT-001',
      categoryName: 'Furniture',
      subcategoryId: 'SUB-CHR',
      subcategoryName: 'Chair',
      itemType: 'Student Chair with Writing Pad',
      purchaseDate: '2024-08-20',
      purchasePrice: 2900.00,
      quantity: 30,
      totalAmount: 87000.00,
      invoiceNumber: 'INV-GI-9921',
      invoiceDate: '2024-08-18',
      warrantyExpiry: '2027-08-20 (3 Years)',
      notes: 'First year engineering lecture hall setup.'
    },
    {
      id: 'PUR-2025-005',
      assetId: 'AST-002',
      assetName: 'Student Chair with Wooden Writing Pad',
      vendorId: 'VND-004',
      vendorName: 'Godrej Interio Commercial',
      categoryId: 'CAT-001',
      categoryName: 'Furniture',
      subcategoryId: 'SUB-CHR',
      subcategoryName: 'Chair',
      itemType: 'Student Chair with Writing Pad',
      purchaseDate: '2025-07-12',
      purchasePrice: 3100.00,
      quantity: 20,
      totalAmount: 62000.00,
      invoiceNumber: 'INV-GI-1142',
      invoiceDate: '2025-07-10',
      warrantyExpiry: '2028-07-12 (3 Years)',
      notes: 'Lecture hall CS-101 replacement quota.'
    },
    {
      id: 'PUR-2026-006',
      assetId: 'AST-002',
      assetName: 'Student Chair with Wooden Writing Pad',
      vendorId: 'VND-004',
      vendorName: 'Godrej Interio Commercial',
      categoryId: 'CAT-001',
      categoryName: 'Furniture',
      subcategoryId: 'SUB-CHR',
      subcategoryName: 'Chair',
      itemType: 'Student Chair with Writing Pad',
      purchaseDate: '2026-02-05',
      purchasePrice: 3200.00,
      quantity: 10,
      totalAmount: 32000.00,
      invoiceNumber: 'INV-GI-2034',
      invoiceDate: '2026-02-02',
      warrantyExpiry: '2029-02-05 (3 Years)',
      notes: 'Supplementary student seating.'
    },
    {
      id: 'PUR-2024-007',
      assetId: 'AST-003',
      assetName: 'Moulded Polypropylene Student Chair',
      vendorId: 'VND-002',
      vendorName: 'ErgoDesign Workspaces',
      categoryId: 'CAT-001',
      categoryName: 'Furniture',
      subcategoryId: 'SUB-CHR',
      subcategoryName: 'Chair',
      itemType: 'Student Chair',
      purchaseDate: '2024-05-18',
      purchasePrice: 1750.00,
      quantity: 40,
      totalAmount: 70000.00,
      invoiceNumber: 'INV-ED-5421',
      invoiceDate: '2024-05-15',
      warrantyExpiry: '2026-05-18 (2 Years)',
      notes: 'Mechanical dept drawing hall seating.'
    },
    {
      id: 'PUR-2025-008',
      assetId: 'AST-003',
      assetName: 'Moulded Polypropylene Student Chair',
      vendorId: 'VND-004',
      vendorName: 'Godrej Interio Commercial',
      categoryId: 'CAT-001',
      categoryName: 'Furniture',
      subcategoryId: 'SUB-CHR',
      subcategoryName: 'Chair',
      itemType: 'Student Chair',
      purchaseDate: '2025-06-25',
      purchasePrice: 1850.00,
      quantity: 25,
      totalAmount: 46250.00,
      invoiceNumber: 'INV-GI-8831',
      invoiceDate: '2025-06-22',
      warrantyExpiry: '2027-06-25 (2 Years)',
      notes: 'Classroom ME-101 additional order.'
    },
    {
      id: 'PUR-2024-009',
      assetId: 'AST-004',
      assetName: 'Executive High-Back Leatherette Faculty Chair',
      vendorId: 'VND-002',
      vendorName: 'ErgoDesign Workspaces',
      categoryId: 'CAT-001',
      categoryName: 'Furniture',
      subcategoryId: 'SUB-CHR',
      subcategoryName: 'Chair',
      itemType: 'Faculty Chair',
      purchaseDate: '2024-11-10',
      purchasePrice: 14000.00,
      quantity: 2,
      totalAmount: 28000.00,
      invoiceNumber: 'INV-ED-9002',
      invoiceDate: '2024-11-08',
      warrantyExpiry: '2027-11-10 (3 Years)',
      notes: 'Principal & Vice Principal chambers.'
    },
    {
      id: 'PUR-2025-010',
      assetId: 'AST-004',
      assetName: 'Executive High-Back Leatherette Faculty Chair',
      vendorId: 'VND-002',
      vendorName: 'ErgoDesign Workspaces',
      categoryId: 'CAT-001',
      categoryName: 'Furniture',
      subcategoryId: 'SUB-CHR',
      subcategoryName: 'Chair',
      itemType: 'Faculty Chair',
      purchaseDate: '2025-10-15',
      purchasePrice: 15500.00,
      quantity: 4,
      totalAmount: 62000.00,
      invoiceNumber: 'INV-ED-9421',
      invoiceDate: '2025-10-12',
      warrantyExpiry: '2028-10-15 (3 Years)',
      notes: 'Senior Professor cabins in Admin Block.'
    },
    {
      id: 'PUR-2024-011',
      assetId: 'AST-007',
      assetName: 'Granite Top 3-Person Student Chemistry Lab Table',
      vendorId: 'VND-002',
      vendorName: 'ErgoDesign Workspaces',
      categoryId: 'CAT-002',
      categoryName: 'Furniture',
      subcategoryId: 'SUB-TBL',
      subcategoryName: 'Table',
      itemType: 'Student Table',
      purchaseDate: '2024-04-12',
      purchasePrice: 26000.00,
      quantity: 6,
      totalAmount: 156000.00,
      invoiceNumber: 'INV-ED-3341',
      invoiceDate: '2024-04-10',
      warrantyExpiry: '2029-04-12 (5 Years)',
      notes: 'Chemistry Laboratory Phase 1 renovation.'
    },
    {
      id: 'PUR-2025-012',
      assetId: 'AST-007',
      assetName: 'Granite Top 3-Person Student Chemistry Lab Table',
      vendorId: 'VND-002',
      vendorName: 'ErgoDesign Workspaces',
      categoryId: 'CAT-002',
      categoryName: 'Furniture',
      subcategoryId: 'SUB-TBL',
      subcategoryName: 'Table',
      itemType: 'Student Table',
      purchaseDate: '2025-11-20',
      purchasePrice: 28500.00,
      quantity: 6,
      totalAmount: 171000.00,
      invoiceNumber: 'INV-ED-7821',
      invoiceDate: '2025-11-18',
      warrantyExpiry: '2030-11-20 (5 Years)',
      notes: 'Chemistry Laboratory Phase 2 expansion.'
    },
    {
      id: 'PUR-2025-013',
      assetId: 'AST-009',
      assetName: 'Executive Teak Wood Faculty Work Desk',
      vendorId: 'VND-004',
      vendorName: 'Godrej Interio Commercial',
      categoryId: 'CAT-002',
      categoryName: 'Furniture',
      subcategoryId: 'SUB-TBL',
      subcategoryName: 'Table',
      itemType: 'Faculty Table',
      purchaseDate: '2025-01-20',
      purchasePrice: 21000.00,
      quantity: 2,
      totalAmount: 42000.00,
      invoiceNumber: 'INV-GI-3921',
      invoiceDate: '2025-01-18',
      warrantyExpiry: '2030-01-20 (5 Years)',
      notes: 'ECE Department Professor desks.'
    },
    {
      id: 'PUR-2026-014',
      assetId: 'AST-009',
      assetName: 'Executive Teak Wood Faculty Work Desk',
      vendorId: 'VND-004',
      vendorName: 'Godrej Interio Commercial',
      categoryId: 'CAT-002',
      categoryName: 'Furniture',
      subcategoryId: 'SUB-TBL',
      subcategoryName: 'Table',
      itemType: 'Faculty Table',
      purchaseDate: '2026-01-10',
      purchasePrice: 22500.00,
      quantity: 2,
      totalAmount: 45000.00,
      invoiceNumber: 'INV-GI-5011',
      invoiceDate: '2026-01-08',
      warrantyExpiry: '2031-01-10 (5 Years)',
      notes: 'ECE Lab 2 Faculty workstations.'
    },
    {
      id: 'PUR-2024-015',
      assetId: 'AST-015',
      assetName: 'High-Lumen 4K Laser Classroom Projector',
      vendorId: 'VND-001',
      vendorName: 'Apex AV Solutions',
      categoryId: 'CAT-004',
      categoryName: 'Electronics',
      subcategoryId: 'SUB-PRJ',
      subcategoryName: 'Projector',
      itemType: 'Laser Projector',
      purchaseDate: '2024-09-15',
      purchasePrice: 82000.00,
      quantity: 2,
      totalAmount: 164000.00,
      invoiceNumber: 'INV-AV-2024-71',
      invoiceDate: '2024-09-12',
      warrantyExpiry: '2027-09-15 (3 Years Onsite)',
      notes: 'Smart Seminar Hall 1 & 2 installation.'
    },
    {
      id: 'PUR-2025-016',
      assetId: 'AST-015',
      assetName: 'High-Lumen 4K Laser Classroom Projector',
      vendorId: 'VND-001',
      vendorName: 'Apex AV Solutions',
      categoryId: 'CAT-004',
      categoryName: 'Electronics',
      subcategoryId: 'SUB-PRJ',
      subcategoryName: 'Projector',
      itemType: 'Laser Projector',
      purchaseDate: '2025-08-10',
      purchasePrice: 85000.00,
      quantity: 4,
      totalAmount: 340000.00,
      invoiceNumber: 'INV-AV-2025-19',
      invoiceDate: '2025-08-08',
      warrantyExpiry: '2028-08-10 (3 Years Onsite)',
      notes: 'Multimedia classrooms upgrade batch.'
    },
    {
      id: 'PUR-2026-017',
      assetId: 'AST-015',
      assetName: 'High-Lumen 4K Laser Classroom Projector',
      vendorId: 'VND-001',
      vendorName: 'Apex AV Solutions',
      categoryId: 'CAT-004',
      categoryName: 'Electronics',
      subcategoryId: 'SUB-PRJ',
      subcategoryName: 'Projector',
      itemType: 'Laser Projector',
      purchaseDate: '2026-03-01',
      purchasePrice: 88000.00,
      quantity: 2,
      totalAmount: 176000.00,
      invoiceNumber: 'INV-AV-2026-04',
      invoiceDate: '2026-02-27',
      warrantyExpiry: '2029-03-01 (3 Years Onsite)',
      notes: 'Auditorium supplementary projection system.'
    },
    {
      id: 'PUR-2025-018',
      assetId: 'AST-016',
      assetName: 'Interactive Multi-Touch Smart Whiteboard',
      vendorId: 'VND-001',
      vendorName: 'Apex AV Solutions',
      categoryId: 'CAT-003',
      categoryName: 'Furniture',
      subcategoryId: 'SUB-BRD',
      subcategoryName: 'Boards',
      itemType: 'Interactive Smart Board',
      purchaseDate: '2025-03-10',
      purchasePrice: 115000.00,
      quantity: 3,
      totalAmount: 345000.00,
      invoiceNumber: 'INV-AV-2025-33',
      invoiceDate: '2025-03-08',
      warrantyExpiry: '2028-03-10 (3 Years)',
      notes: 'Smart classroom interactive teaching boards.'
    },
    {
      id: 'PUR-2026-019',
      assetId: 'AST-016',
      assetName: 'Interactive Multi-Touch Smart Whiteboard',
      vendorId: 'VND-001',
      vendorName: 'Apex AV Solutions',
      categoryId: 'CAT-003',
      categoryName: 'Furniture',
      subcategoryId: 'SUB-BRD',
      subcategoryName: 'Boards',
      itemType: 'Interactive Smart Board',
      purchaseDate: '2026-02-18',
      purchasePrice: 122000.00,
      quantity: 2,
      totalAmount: 244000.00,
      invoiceNumber: 'INV-AV-2026-12',
      invoiceDate: '2026-02-15',
      warrantyExpiry: '2029-02-18 (3 Years)',
      notes: 'Virtual classroom 3 & 4 additions.'
    },
    {
      id: 'PUR-2024-020',
      assetId: 'AST-020',
      assetName: 'Dell OptiPlex Desktop Workstation',
      vendorId: 'VND-005',
      vendorName: 'Dell India Enterprise',
      categoryId: 'CAT-004',
      categoryName: 'Electronics',
      subcategoryId: 'SUB-CMP',
      subcategoryName: 'Computer',
      itemType: 'Desktop Workstation',
      purchaseDate: '2024-07-10',
      purchasePrice: 58000.00,
      quantity: 15,
      totalAmount: 870000.00,
      invoiceNumber: 'INV-DELL-2024-101',
      invoiceDate: '2024-07-08',
      warrantyExpiry: '2027-07-10 (3 Years ProSupport)',
      notes: 'Initial purchase for CSE Data Science Lab.'
    },
    {
      id: 'PUR-2025-021',
      assetId: 'AST-020',
      assetName: 'Dell OptiPlex Desktop Workstation',
      vendorId: 'VND-005',
      vendorName: 'Dell India Enterprise',
      categoryId: 'CAT-004',
      categoryName: 'Electronics',
      subcategoryId: 'SUB-CMP',
      subcategoryName: 'Computer',
      itemType: 'Desktop Workstation',
      purchaseDate: '2025-03-15',
      purchasePrice: 62000.00,
      quantity: 15,
      totalAmount: 930000.00,
      invoiceNumber: 'INV-DELL-2025-045',
      invoiceDate: '2025-03-12',
      warrantyExpiry: '2028-03-15 (3 Years ProSupport)',
      notes: 'Batch 2 order with updated 13th Gen Intel processors.'
    },
    {
      id: 'PUR-2026-022',
      assetId: 'AST-020',
      assetName: 'Dell OptiPlex Desktop Workstation',
      vendorId: 'VND-005',
      vendorName: 'Dell India Enterprise',
      categoryId: 'CAT-004',
      categoryName: 'Electronics',
      subcategoryId: 'SUB-CMP',
      subcategoryName: 'Computer',
      itemType: 'Desktop Workstation',
      purchaseDate: '2026-01-20',
      purchasePrice: 65000.00,
      quantity: 10,
      totalAmount: 650000.00,
      invoiceNumber: 'INV-DELL-2026-009',
      invoiceDate: '2026-01-18',
      warrantyExpiry: '2029-01-20 (3 Years ProSupport)',
      notes: 'Latest purchase with 32GB RAM upgrade.'
    },
    {
      id: 'PUR-2025-023',
      assetId: 'AST-021',
      assetName: 'Dell Latitude Core i7 Faculty Laptop',
      vendorId: 'VND-005',
      vendorName: 'Dell India Enterprise',
      categoryId: 'CAT-004',
      categoryName: 'Electronics',
      subcategoryId: 'SUB-CMP',
      subcategoryName: 'Computer',
      itemType: 'Laptop',
      purchaseDate: '2025-02-14',
      purchasePrice: 72000.00,
      quantity: 5,
      totalAmount: 360000.00,
      invoiceNumber: 'INV-DELL-2025-022',
      invoiceDate: '2025-02-12',
      warrantyExpiry: '2028-02-14 (3 Years Complete Care)',
      notes: 'Issued to Department Heads for academic administration.'
    },
    {
      id: 'PUR-2026-024',
      assetId: 'AST-021',
      assetName: 'Dell Latitude Core i7 Faculty Laptop',
      vendorId: 'VND-005',
      vendorName: 'Dell India Enterprise',
      categoryId: 'CAT-004',
      categoryName: 'Electronics',
      subcategoryId: 'SUB-CMP',
      subcategoryName: 'Computer',
      itemType: 'Laptop',
      purchaseDate: '2026-02-10',
      purchasePrice: 76500.00,
      quantity: 5,
      totalAmount: 382500.00,
      invoiceNumber: 'INV-DELL-2026-015',
      invoiceDate: '2026-02-08',
      warrantyExpiry: '2029-02-10 (3 Years Complete Care)',
      notes: 'Issued to newly joined senior faculty members.'
    },
    {
      id: 'PUR-2025-025',
      assetId: 'AST-022',
      assetName: 'Matrix Smart UPS & Power Backup 5KVA',
      vendorId: 'VND-003',
      vendorName: 'Matrix Electronics Care',
      categoryId: 'CAT-004',
      categoryName: 'Electronics',
      subcategoryId: 'SUB-PWR',
      subcategoryName: 'Power & UPS',
      itemType: 'Online UPS',
      purchaseDate: '2025-04-18',
      purchasePrice: 44000.00,
      quantity: 4,
      totalAmount: 176000.00,
      invoiceNumber: 'INV-MTR-8812',
      invoiceDate: '2025-04-15',
      warrantyExpiry: '2027-04-18 (2 Years Battery + Inverter)',
      notes: 'Power backup for CSE Server Room and IoT Lab.'
    },
    {
      id: 'PUR-2026-026',
      assetId: 'AST-022',
      assetName: 'Matrix Smart UPS & Power Backup 5KVA',
      vendorId: 'VND-003',
      vendorName: 'Matrix Electronics Care',
      categoryId: 'CAT-004',
      categoryName: 'Electronics',
      subcategoryId: 'SUB-PWR',
      subcategoryName: 'Power & UPS',
      itemType: 'Online UPS',
      purchaseDate: '2026-02-28',
      purchasePrice: 46500.00,
      quantity: 2,
      totalAmount: 93000.00,
      invoiceNumber: 'INV-MTR-9901',
      invoiceDate: '2026-02-25',
      warrantyExpiry: '2028-02-28 (2 Years Battery + Inverter)',
      notes: 'Power backup for AI & Data Science Server Rack.'
    },

    // =========================================================================
    // 3. LABORATORY CATEGORY PROCUREMENT TRANSACTIONS
    // =========================================================================
    {
      id: 'PUR-2024-027',
      assetId: 'AST-101',
      assetName: 'Digital Precision Electronic Analytical Laboratory Balance 0.1mg',
      vendorId: 'VND-006',
      vendorName: 'ThermoFisher Scientific Lab Solutions',
      categoryId: 'CAT-LAB',
      categoryName: 'Laboratory',
      subcategoryId: 'SUB-ANA',
      subcategoryName: 'Analytical Instruments',
      itemType: 'Digital Precision Analytical Balance',
      purchaseDate: '2024-04-12',
      purchasePrice: 42000.00,
      quantity: 4,
      totalAmount: 168000.00,
      invoiceNumber: 'INV-TF-2024-104',
      invoiceDate: '2024-04-10',
      warrantyExpiry: '2027-04-12 (3 Years Calibration)',
      notes: 'Procured for Science & Humanities Chemistry Advanced Testing Lab.'
    },
    {
      id: 'PUR-2025-028',
      assetId: 'AST-101',
      assetName: 'Digital Precision Electronic Analytical Laboratory Balance 0.1mg',
      vendorId: 'VND-006',
      vendorName: 'ThermoFisher Scientific Lab Solutions',
      categoryId: 'CAT-LAB',
      categoryName: 'Laboratory',
      subcategoryId: 'SUB-ANA',
      subcategoryName: 'Analytical Instruments',
      itemType: 'Digital Precision Analytical Balance',
      purchaseDate: '2025-03-18',
      purchasePrice: 44500.00,
      quantity: 6,
      totalAmount: 267000.00,
      invoiceNumber: 'INV-TF-2025-219',
      invoiceDate: '2025-03-15',
      warrantyExpiry: '2028-03-18 (3 Years Calibration)',
      notes: 'Batch addition for Biotechnology & Material Science Lab.'
    },
    {
      id: 'PUR-2026-029',
      assetId: 'AST-101',
      assetName: 'Digital Precision Electronic Analytical Laboratory Balance 0.1mg',
      vendorId: 'VND-006',
      vendorName: 'ThermoFisher Scientific Lab Solutions',
      categoryId: 'CAT-LAB',
      categoryName: 'Laboratory',
      subcategoryId: 'SUB-ANA',
      subcategoryName: 'Analytical Instruments',
      itemType: 'Digital Precision Analytical Balance',
      purchaseDate: '2026-01-22',
      purchasePrice: 46200.00,
      quantity: 3,
      totalAmount: 138600.00,
      invoiceNumber: 'INV-TF-2026-041',
      invoiceDate: '2026-01-20',
      warrantyExpiry: '2029-01-22 (3 Years Calibration)',
      notes: 'Replenishment for PG Nanotechnology Research Section.'
    },
    {
      id: 'PUR-2024-030',
      assetId: 'AST-102',
      assetName: 'Binocular Research Compound Microscope with LED Illumination',
      vendorId: 'VND-006',
      vendorName: 'ThermoFisher Scientific Lab Solutions',
      categoryId: 'CAT-LAB',
      categoryName: 'Laboratory',
      subcategoryId: 'SUB-OPT',
      subcategoryName: 'Optical & Microscopy',
      itemType: 'Binocular Research Compound Microscope',
      purchaseDate: '2024-07-15',
      purchasePrice: 18500.00,
      quantity: 10,
      totalAmount: 185000.00,
      invoiceNumber: 'INV-TF-2024-388',
      invoiceDate: '2024-07-12',
      warrantyExpiry: '2027-07-15 (3 Years Optics)',
      notes: 'First-year Biology & Microscopy practical hall installation.'
    },
    {
      id: 'PUR-2025-031',
      assetId: 'AST-102',
      assetName: 'Binocular Research Compound Microscope with LED Illumination',
      vendorId: 'VND-006',
      vendorName: 'ThermoFisher Scientific Lab Solutions',
      categoryId: 'CAT-LAB',
      categoryName: 'Laboratory',
      subcategoryId: 'SUB-OPT',
      subcategoryName: 'Optical & Microscopy',
      itemType: 'Binocular Research Compound Microscope',
      purchaseDate: '2025-06-20',
      purchasePrice: 19800.00,
      quantity: 15,
      totalAmount: 297000.00,
      invoiceNumber: 'INV-TF-2025-502',
      invoiceDate: '2025-06-18',
      warrantyExpiry: '2028-06-20 (3 Years Optics)',
      notes: 'Capacity expansion for Microbiology and Pathology practical lab.'
    },
    {
      id: 'PUR-2026-032',
      assetId: 'AST-102',
      assetName: 'Binocular Research Compound Microscope with LED Illumination',
      vendorId: 'VND-006',
      vendorName: 'ThermoFisher Scientific Lab Solutions',
      categoryId: 'CAT-LAB',
      categoryName: 'Laboratory',
      subcategoryId: 'SUB-OPT',
      subcategoryName: 'Optical & Microscopy',
      itemType: 'Binocular Research Compound Microscope',
      purchaseDate: '2026-02-14',
      purchasePrice: 21000.00,
      quantity: 8,
      totalAmount: 168000.00,
      invoiceNumber: 'INV-TF-2026-092',
      invoiceDate: '2026-02-11',
      warrantyExpiry: '2029-02-14 (3 Years Optics)',
      notes: 'Advanced high-magnification immersion oil units.'
    },
    {
      id: 'PUR-2024-033',
      assetId: 'AST-103',
      assetName: 'Horizontal Laminar Air Flow Chamber Ultra Clean Workstation',
      vendorId: 'VND-006',
      vendorName: 'ThermoFisher Scientific Lab Solutions',
      categoryId: 'CAT-LAB',
      categoryName: 'Laboratory',
      subcategoryId: 'SUB-BIO',
      subcategoryName: 'Glassware & Biosafety',
      itemType: 'Horizontal Laminar Air Flow Chamber',
      purchaseDate: '2024-09-05',
      purchasePrice: 78000.00,
      quantity: 2,
      totalAmount: 156000.00,
      invoiceNumber: 'INV-TF-2024-610',
      invoiceDate: '2024-09-02',
      warrantyExpiry: '2026-09-05 (2 Years HEPA & Motor)',
      notes: 'Sterile culture inoculation workstation for Tissue Culture Lab.'
    },
    {
      id: 'PUR-2025-034',
      assetId: 'AST-103',
      assetName: 'Horizontal Laminar Air Flow Chamber Ultra Clean Workstation',
      vendorId: 'VND-006',
      vendorName: 'ThermoFisher Scientific Lab Solutions',
      categoryId: 'CAT-LAB',
      categoryName: 'Laboratory',
      subcategoryId: 'SUB-BIO',
      subcategoryName: 'Glassware & Biosafety',
      itemType: 'Horizontal Laminar Air Flow Chamber',
      purchaseDate: '2025-08-12',
      purchasePrice: 82500.00,
      quantity: 3,
      totalAmount: 247500.00,
      invoiceNumber: 'INV-TF-2025-780',
      invoiceDate: '2025-08-10',
      warrantyExpiry: '2027-08-12 (2 Years HEPA & Motor)',
      notes: 'HEPA 99.99% certified bio-safety inoculation cabinets.'
    },
    {
      id: 'PUR-2024-035',
      assetId: 'AST-104',
      assetName: 'Pelton Wheel Turbine Fluid Mechanics Rig',
      vendorId: 'VND-006',
      vendorName: 'ThermoFisher Scientific Lab Solutions',
      categoryId: 'CAT-LAB',
      categoryName: 'Laboratory',
      subcategoryId: 'SUB-ENG',
      subcategoryName: 'Engineering & Testing',
      itemType: 'Pelton Wheel Turbine Fluid Mechanics Rig',
      purchaseDate: '2024-05-20',
      purchasePrice: 145000.00,
      quantity: 1,
      totalAmount: 145000.00,
      invoiceNumber: 'INV-TF-2024-245',
      invoiceDate: '2024-05-18',
      warrantyExpiry: '2027-05-20 (3 Years Comprehensive)',
      notes: 'Heavy engineering test apparatus for Mechanical Fluid Mechanics Lab.'
    },
    {
      id: 'PUR-2025-036',
      assetId: 'AST-104',
      assetName: 'Pelton Wheel Turbine Fluid Mechanics Rig',
      vendorId: 'VND-006',
      vendorName: 'ThermoFisher Scientific Lab Solutions',
      categoryId: 'CAT-LAB',
      categoryName: 'Laboratory',
      subcategoryId: 'SUB-ENG',
      subcategoryName: 'Engineering & Testing',
      itemType: 'Pelton Wheel Turbine Fluid Mechanics Rig',
      purchaseDate: '2025-10-15',
      purchasePrice: 152000.00,
      quantity: 1,
      totalAmount: 152000.00,
      invoiceNumber: 'INV-TF-2025-911',
      invoiceDate: '2025-10-12',
      warrantyExpiry: '2028-10-15 (3 Years Comprehensive)',
      notes: 'Second test bed unit for hydraulic power and efficiency experiments.'
    },

    // =========================================================================
    // 4. IT HARDWARE CATEGORY PROCUREMENT TRANSACTIONS
    // =========================================================================
    {
      id: 'PUR-2024-037',
      assetId: 'AST-201',
      assetName: 'All-in-One Desktop Core i7 Workstation (32GB RAM, 1TB SSD)',
      vendorId: 'VND-005',
      vendorName: 'Dell India Enterprise',
      categoryId: 'CAT-IT',
      categoryName: 'IT Hardware',
      subcategoryId: 'SUB-COM',
      subcategoryName: 'Computing & Workstations',
      itemType: 'All-in-One Desktop Core i7 Workstation',
      purchaseDate: '2024-03-25',
      purchasePrice: 68000.00,
      quantity: 25,
      totalAmount: 1700000.00,
      invoiceNumber: 'INV-DELL-2024-118',
      invoiceDate: '2024-03-22',
      warrantyExpiry: '2027-03-25 (3 Years ProSupport NBD)',
      notes: 'CSE Department Main Software Lab 1 infrastructure upgrade.'
    },
    {
      id: 'PUR-2025-038',
      assetId: 'AST-201',
      assetName: 'All-in-One Desktop Core i7 Workstation (32GB RAM, 1TB SSD)',
      vendorId: 'VND-005',
      vendorName: 'Dell India Enterprise',
      categoryId: 'CAT-IT',
      categoryName: 'IT Hardware',
      subcategoryId: 'SUB-COM',
      subcategoryName: 'Computing & Workstations',
      itemType: 'All-in-One Desktop Core i7 Workstation',
      purchaseDate: '2025-04-10',
      purchasePrice: 71500.00,
      quantity: 30,
      totalAmount: 2145000.00,
      invoiceNumber: 'INV-DELL-2025-410',
      invoiceDate: '2025-04-08',
      warrantyExpiry: '2028-04-10 (3 Years ProSupport NBD)',
      notes: 'AI & Data Science High-Performance Lab deployment.'
    },
    {
      id: 'PUR-2026-039',
      assetId: 'AST-201',
      assetName: 'All-in-One Desktop Core i7 Workstation (32GB RAM, 1TB SSD)',
      vendorId: 'VND-005',
      vendorName: 'Dell India Enterprise',
      categoryId: 'CAT-IT',
      categoryName: 'IT Hardware',
      subcategoryId: 'SUB-COM',
      subcategoryName: 'Computing & Workstations',
      itemType: 'All-in-One Desktop Core i7 Workstation',
      purchaseDate: '2026-01-30',
      purchasePrice: 74000.00,
      quantity: 15,
      totalAmount: 1110000.00,
      invoiceNumber: 'INV-DELL-2026-088',
      invoiceDate: '2026-01-27',
      warrantyExpiry: '2029-01-30 (3 Years ProSupport NBD)',
      notes: 'Cybersecurity & Cloud Computing specialized lab batch.'
    },
    {
      id: 'PUR-2024-040',
      assetId: 'AST-202',
      assetName: '24-Port Gigabit Managed PoE+ Network Switch',
      vendorId: 'VND-007',
      vendorName: 'Cisco Networks & IT Infrastructure',
      categoryId: 'CAT-IT',
      categoryName: 'IT Hardware',
      subcategoryId: 'SUB-NET',
      subcategoryName: 'Networking & Infrastructure',
      itemType: '24-Port Gigabit Managed PoE+ Network Switch',
      purchaseDate: '2024-06-18',
      purchasePrice: 38000.00,
      quantity: 6,
      totalAmount: 228000.00,
      invoiceNumber: 'INV-CSC-2024-092',
      invoiceDate: '2024-06-15',
      warrantyExpiry: '2029-06-18 (5 Years Enhanced Limited Lifetime)',
      notes: 'Core network backbone switches for Engineering Block Server Rack.'
    },
    {
      id: 'PUR-2025-041',
      assetId: 'AST-202',
      assetName: '24-Port Gigabit Managed PoE+ Network Switch',
      vendorId: 'VND-007',
      vendorName: 'Cisco Networks & IT Infrastructure',
      categoryId: 'CAT-IT',
      categoryName: 'IT Hardware',
      subcategoryId: 'SUB-NET',
      subcategoryName: 'Networking & Infrastructure',
      itemType: '24-Port Gigabit Managed PoE+ Network Switch',
      purchaseDate: '2025-07-22',
      purchasePrice: 41000.00,
      quantity: 8,
      totalAmount: 328000.00,
      invoiceNumber: 'INV-CSC-2025-315',
      invoiceDate: '2025-07-20',
      warrantyExpiry: '2030-07-22 (5 Years Enhanced Limited Lifetime)',
      notes: 'Campus Wi-Fi PoE power and smart classroom LAN integration.'
    },
    {
      id: 'PUR-2026-042',
      assetId: 'AST-202',
      assetName: '24-Port Gigabit Managed PoE+ Network Switch',
      vendorId: 'VND-007',
      vendorName: 'Cisco Networks & IT Infrastructure',
      categoryId: 'CAT-IT',
      categoryName: 'IT Hardware',
      subcategoryId: 'SUB-NET',
      subcategoryName: 'Networking & Infrastructure',
      itemType: '24-Port Gigabit Managed PoE+ Network Switch',
      purchaseDate: '2026-02-18',
      purchasePrice: 43500.00,
      quantity: 4,
      totalAmount: 174000.00,
      invoiceNumber: 'INV-CSC-2026-044',
      invoiceDate: '2026-02-15',
      warrantyExpiry: '2031-02-18 (5 Years Enhanced Limited Lifetime)',
      notes: 'Library Digital Resource Center & Admin wing network switches.'
    },
    {
      id: 'PUR-2024-043',
      assetId: 'AST-203',
      assetName: '27-inch 4K UHD IPS Professional Monitor',
      vendorId: 'VND-005',
      vendorName: 'Dell India Enterprise',
      categoryId: 'CAT-IT',
      categoryName: 'IT Hardware',
      subcategoryId: 'SUB-DIS',
      subcategoryName: 'Displays & Peripherals',
      itemType: '27-inch 4K UHD IPS Professional Monitor',
      purchaseDate: '2024-08-14',
      purchasePrice: 24500.00,
      quantity: 12,
      totalAmount: 294000.00,
      invoiceNumber: 'INV-DELL-2024-512',
      invoiceDate: '2024-08-11',
      warrantyExpiry: '2027-08-14 (3 Years Advanced Exchange)',
      notes: 'Design & Multimedia faculty workstations dual-monitor setup.'
    },
    {
      id: 'PUR-2025-044',
      assetId: 'AST-203',
      assetName: '27-inch 4K UHD IPS Professional Monitor',
      vendorId: 'VND-005',
      vendorName: 'Dell India Enterprise',
      categoryId: 'CAT-IT',
      categoryName: 'IT Hardware',
      subcategoryId: 'SUB-DIS',
      subcategoryName: 'Displays & Peripherals',
      itemType: '27-inch 4K UHD IPS Professional Monitor',
      purchaseDate: '2025-09-10',
      purchasePrice: 26000.00,
      quantity: 20,
      totalAmount: 520000.00,
      invoiceNumber: 'INV-DELL-2025-789',
      invoiceDate: '2025-09-08',
      warrantyExpiry: '2028-09-10 (3 Years Advanced Exchange)',
      notes: 'CAD / CAM Engineering Design Lab multi-display setup.'
    },
    {
      id: 'PUR-2026-045',
      assetId: 'AST-203',
      assetName: '27-inch 4K UHD IPS Professional Monitor',
      vendorId: 'VND-005',
      vendorName: 'Dell India Enterprise',
      categoryId: 'CAT-IT',
      categoryName: 'IT Hardware',
      subcategoryId: 'SUB-DIS',
      subcategoryName: 'Displays & Peripherals',
      itemType: '27-inch 4K UHD IPS Professional Monitor',
      purchaseDate: '2026-01-18',
      purchasePrice: 27200.00,
      quantity: 10,
      totalAmount: 272000.00,
      invoiceNumber: 'INV-DELL-2026-031',
      invoiceDate: '2026-01-15',
      warrantyExpiry: '2029-01-18 (3 Years Advanced Exchange)',
      notes: 'Research Scholar workstation monitors.'
    },
    {
      id: 'PUR-2024-046',
      assetId: 'AST-204',
      assetName: 'Online Modular Rackmount UPS 5KVA',
      vendorId: 'VND-003',
      vendorName: 'Matrix Electronics Care',
      categoryId: 'CAT-IT',
      categoryName: 'IT Hardware',
      subcategoryId: 'SUB-PWR',
      subcategoryName: 'Power & UPS',
      itemType: 'Online Modular Rackmount UPS 5KVA',
      purchaseDate: '2024-11-05',
      purchasePrice: 52000.00,
      quantity: 3,
      totalAmount: 156000.00,
      invoiceNumber: 'INV-MTR-2024-550',
      invoiceDate: '2024-11-02',
      warrantyExpiry: '2026-11-05 (2 Years Battery & Inverter)',
      notes: 'Clean zero-switchover power backup for Cloud & Virtualization racks.'
    },
    {
      id: 'PUR-2025-047',
      assetId: 'AST-204',
      assetName: 'Online Modular Rackmount UPS 5KVA',
      vendorId: 'VND-003',
      vendorName: 'Matrix Electronics Care',
      categoryId: 'CAT-IT',
      categoryName: 'IT Hardware',
      subcategoryId: 'SUB-PWR',
      subcategoryName: 'Power & UPS',
      itemType: 'Online Modular Rackmount UPS 5KVA',
      purchaseDate: '2025-11-20',
      purchasePrice: 55000.00,
      quantity: 4,
      totalAmount: 220000.00,
      invoiceNumber: 'INV-MTR-2025-880',
      invoiceDate: '2025-11-17',
      warrantyExpiry: '2027-11-20 (2 Years Battery & Inverter)',
      notes: 'Distributed server room UPS power protection.'
    },
    {
      id: 'PUR-2026-048',
      assetId: 'AST-204',
      assetName: 'Online Modular Rackmount UPS 5KVA',
      vendorId: 'VND-003',
      vendorName: 'Matrix Electronics Care',
      categoryId: 'CAT-IT',
      categoryName: 'IT Hardware',
      subcategoryId: 'SUB-PWR',
      subcategoryName: 'Power & UPS',
      itemType: 'Online Modular Rackmount UPS 5KVA',
      purchaseDate: '2026-02-05',
      purchasePrice: 58000.00,
      quantity: 2,
      totalAmount: 116000.00,
      invoiceNumber: 'INV-MTR-2026-077',
      invoiceDate: '2026-02-02',
      warrantyExpiry: '2028-02-05 (2 Years Battery & Inverter)',
      notes: 'Central NOC Room dedicated dual-conversion power unit.'
    }
  ];

  localStorage.setItem('purchase_history_list', JSON.stringify(initial));
  return initial;
};

const purchaseHistorySlice = createSlice({
  name: 'purchaseHistory',
  initialState: {
    list: getInitialPurchaseHistory(),
    loading: false,
    error: null,
    stats: null,
    selectedAssetId: null,
  },
  reducers: {
    setPurchaseHistoryList: (state, action) => {
      state.list = action.payload;
      localStorage.setItem('purchase_history_list', JSON.stringify(state.list));
    },
    addPurchaseHistoryRecord: (state, action) => {
      const exists = state.list.some(p => p.id === action.payload.id);
      if (!exists) {
        state.list.unshift(action.payload);
      } else {
        const index = state.list.findIndex(p => p.id === action.payload.id);
        if (index !== -1) state.list[index] = action.payload;
      }
      localStorage.setItem('purchase_history_list', JSON.stringify(state.list));
    },
    updatePurchaseHistoryRecord: (state, action) => {
      const index = state.list.findIndex(p => p.id === action.payload.id);
      if (index !== -1) {
        state.list[index] = { ...state.list[index], ...action.payload };
        localStorage.setItem('purchase_history_list', JSON.stringify(state.list));
      }
    },
    deletePurchaseHistoryRecord: (state, action) => {
      state.list = state.list.filter(p => p.id !== action.payload);
      localStorage.setItem('purchase_history_list', JSON.stringify(state.list));
    },
    setPurchaseHistoryStats: (state, action) => {
      state.stats = action.payload;
    },
    setSelectedAssetId: (state, action) => {
      state.selectedAssetId = action.payload;
    }
  }
});

export const {
  setPurchaseHistoryList,
  addPurchaseHistoryRecord,
  updatePurchaseHistoryRecord,
  deletePurchaseHistoryRecord,
  setPurchaseHistoryStats,
  setSelectedAssetId
} = purchaseHistorySlice.actions;

export default purchaseHistorySlice.reducer;
