import { initialAssets } from '../src/store/furnitureSlice.js';

export { initialAssets };

// ─── 1. USERS ───────────────────────────────────────────────────────────────
export const initialUsers = [
  {
    id: 'USR-001',
    username: 'superadmin',
    password: 'password123',
    name: 'Dr. Rajesh Kumar',
    role: 'superadmin',
    department: 'Admin Block',
    email: 'rajesh.kumar@nec.edu.in'
  },
  {
    id: 'USR-002',
    username: 'cs_admin',
    password: 'password123',
    name: 'Prof. Anitha Sharma',
    role: 'deptadmin',
    department: 'Computer Science',
    email: 'anitha.sharma@nec.edu.in'
  },
  {
    id: 'USR-003',
    username: 'mech_admin',
    password: 'password123',
    name: 'Prof. Kavitha Raj',
    role: 'deptadmin',
    department: 'Mechanical',
    email: 'kavitha.raj@nec.edu.in'
  },
  {
    id: 'USR-004',
    username: 'civil_admin',
    password: 'password123',
    name: 'Prof. Aruna Devi',
    role: 'deptadmin',
    department: 'Civil',
    email: 'aruna.devi@nec.edu.in'
  },
  {
    id: 'USR-005',
    username: 'it_admin',
    password: 'password123',
    name: 'Dr. M. Venkatesh',
    role: 'deptadmin',
    department: 'IT',
    email: 'venkatesh.m@nec.edu.in'
  },
  {
    id: 'USR-006',
    username: 'aids_admin',
    password: 'password123',
    name: 'Dr. Nalini Patel',
    role: 'deptadmin',
    department: 'AIDS',
    email: 'nalini.patel@nec.edu.in'
  },
  {
    id: 'USR-007',
    username: 'ece_admin',
    password: 'password123',
    name: 'Prof. Ramesh Nair',
    role: 'deptadmin',
    department: 'ECE',
    email: 'ramesh.nair@nec.edu.in'
  },
  {
    id: 'USR-008',
    username: 'eee_admin',
    password: 'password123',
    name: 'Dr. R. Vijay Anand',
    role: 'deptadmin',
    department: 'EEE',
    email: 'vijayanand.r@nec.edu.in'
  },
  {
    id: 'USR-009',
    username: 'sh_admin',
    password: 'password123',
    name: 'Prof. Dinesh Kumar',
    role: 'deptadmin',
    department: 'Science & Humanities',
    email: 'dinesh.kumar@nec.edu.in'
  },
  {
    id: 'USR-010',
    username: 'admin_officer',
    password: 'password123',
    name: 'Ms. Priya Mehta',
    role: 'deptadmin',
    department: 'Admin Block',
    email: 'priya.mehta@nec.edu.in'
  },
  {
    id: 'USR-011',
    username: 'auditor',
    password: 'password123',
    name: 'Mr. Ravi Shankar',
    role: 'auditor',
    department: 'Admin Block',
    email: 'ravi.shankar@nec.edu.in'
  },
  {
    id: 'USR-012',
    username: 'cs_faculty',
    password: 'password123',
    name: 'Prof. Suresh Babu',
    role: 'faculty',
    department: 'Computer Science',
    email: 'suresh.babu@nec.edu.in'
  },
  {
    id: 'USR-013',
    username: 'chem_faculty',
    password: 'password123',
    name: 'Dr. Lalitha Devi',
    role: 'faculty',
    department: 'Science & Humanities',
    email: 'lalitha.devi@nec.edu.in'
  }
];

// ─── 2. TRANSFERS ───────────────────────────────────────────────────────────
export const initialTransfers = [
  {
    id: 'TRF-001',
    assetId: 'AST-010',
    furniture: 'Optoma Projector System',
    source: 'CS-101',
    destination: 'CS-102',
    requestedBy: 'Prof. Anitha Sharma',
    role: 'Dept Admin',
    department: 'Computer Science',
    date: '2026-09-01',
    status: 'Completed',
    reason: 'Classroom CS-102 scheduled for national online faculty development webinar'
  },
  {
    id: 'TRF-002',
    assetId: 'AST-018',
    furniture: 'Heavy Duty Metal Lathe Toolpost',
    source: 'MECH-Workshop',
    destination: 'MECH-101',
    requestedBy: 'Prof. Kavitha Raj',
    role: 'Dept Admin',
    department: 'Mechanical',
    date: '2026-09-03',
    status: 'Approved',
    reason: 'Demonstration unit required for mechanical fabrication workshop lecture'
  },
  {
    id: 'TRF-003',
    assetId: 'AST-065',
    furniture: 'FPGA Development Trainer Board',
    source: 'ECE-Lab1',
    destination: 'ECE-Lab2',
    requestedBy: 'Prof. Ramesh Nair',
    role: 'Dept Admin',
    department: 'ECE',
    date: '2026-09-05',
    status: 'Pending',
    reason: 'Inter-departmental VLSI layout & FPGA logic simulation lab session'
  },
  {
    id: 'TRF-004',
    assetId: 'AST-085',
    furniture: 'He-Ne Laser Optics Demonstration Unit',
    source: 'SH-PhysicsLab',
    destination: 'SH-101',
    requestedBy: 'Prof. Dinesh Kumar',
    role: 'Dept Admin',
    department: 'Science & Humanities',
    date: '2026-09-06',
    status: 'Rejected',
    reason: 'Laser optical table is calibrated in dark-room setup and cannot be moved'
  },
  {
    id: 'TRF-005',
    assetId: 'AST-095',
    furniture: 'Executive Conference Oval Table',
    source: 'ADM-101',
    destination: 'ADM-Hall',
    requestedBy: 'Ms. Priya Mehta',
    role: 'Dept Admin',
    department: 'Admin Block',
    date: '2026-09-07',
    status: 'Approved',
    reason: 'Scheduled for annual board of governors institutional review meeting'
  },
  {
    id: 'TRF-006',
    assetId: 'AST-099',
    furniture: 'EPSON Laser Fleet Network Printer',
    source: 'ADM-Records',
    destination: 'ADM-101',
    requestedBy: 'Ms. Priya Mehta',
    role: 'Dept Admin',
    department: 'Admin Block',
    date: '2026-09-08',
    status: 'Pending',
    reason: 'High-speed certificate and admission dossier printing requirements'
  }
];

// ─── 3. INSPECTIONS ─────────────────────────────────────────────────────────
export const initialInspections = [
  {
    id: 'INS-001',
    assetId: 'AST-010',
    furniture: 'Optoma Projector System',
    location: 'CS-101',
    condition: 'Fair',
    inspector: 'Mr. Ravi Shankar',
    date: '2026-08-05',
    notes: 'Lamp brightness measured at 2100 lumens. Recommend lamp replacement within 2 months.'
  },
  {
    id: 'INS-002',
    assetId: 'AST-017',
    furniture: 'Precision Universal Testing Machine',
    location: 'MECH-Workshop',
    condition: 'Good',
    inspector: 'Mr. Ravi Shankar',
    date: '2026-08-10',
    notes: 'Hydraulic load cells calibrated to ASTM standards. Test records updated.'
  },
  {
    id: 'INS-003',
    assetId: 'AST-096',
    furniture: 'Ricoh High-Capacity Multifunction Photocopier',
    location: 'ADM-Records',
    condition: 'Fair',
    inspector: 'Mr. Ravi Shankar',
    date: '2026-08-12',
    notes: 'Toner level at 35%. Drum roller scheduled for routine quarterly cleaning.'
  },
  {
    id: 'INS-004',
    assetId: 'AST-001',
    furniture: 'Dell OptiPlex 7090 Desktop Computer',
    location: 'CS-Lab1',
    condition: 'Good',
    inspector: 'Prof. Suresh Babu',
    date: '2026-08-18',
    notes: 'System diagnostics all passed. RAM and SSD health at 100%.'
  },
  {
    id: 'INS-005',
    assetId: 'AST-075',
    furniture: 'Digital Storage Oscilloscope 100MHz',
    location: 'EEE-Lab1',
    condition: 'Good',
    inspector: 'Dr. R. Vijay Anand',
    date: '2026-08-20',
    notes: 'Channel 1 and Channel 2 probes checked and calibrated with test generator.'
  },
  {
    id: 'INS-006',
    assetId: 'AST-092',
    furniture: 'Admin Workstation Dell Precision 3660',
    location: 'ADM-101',
    condition: 'Good',
    inspector: 'Mr. Ravi Shankar',
    date: '2026-08-25',
    notes: 'Enterprise accounting software running smoothly. Dual monitor setup tested.'
  }
];

// ─── 4. NOTIFICATIONS ───────────────────────────────────────────────────────
export const initialNotifications = [
  {
    id: 'NOTIF-001',
    title: 'Asset Updated',
    message: 'Admin Workstation Dell Precision 3660 (AST-092) was updated.',
    time: '10 min ago',
    read: false,
    department: 'Admin Block',
    type: 'asset',
    link: '/assets/AST-092'
  },
  {
    id: 'NOTIF-002',
    title: 'Campus-wide Asset Audit',
    message: 'Quarterly institutional physical asset audit initiated across all departments.',
    time: '1 hour ago',
    read: false,
    department: 'All',
    type: 'system',
    link: '/inspections'
  },
  {
    id: 'NOTIF-003',
    title: 'New Asset Registered',
    message: 'HP LaserJet Enterprise Flow Printer (AST-093) registered in ADM-101.',
    time: '2 hours ago',
    read: false,
    department: 'Admin Block',
    type: 'asset',
    link: '/assets/AST-093'
  },
  {
    id: 'NOTIF-004',
    title: 'Maintenance Logged',
    message: 'Service ticket MNT-001 created for Projector System (AST-010).',
    time: '3 hours ago',
    read: true,
    department: 'Computer Science',
    type: 'maintenance',
    link: '/maintenance'
  },
  {
    id: 'NOTIF-005',
    title: 'Transfer Request Approved',
    message: 'Transfer of Executive Oval Table to ADM-Hall approved by Principal Office.',
    time: '5 hours ago',
    read: true,
    department: 'Admin Block',
    type: 'transfer',
    link: '/transfers'
  }
];

// ─── 5. DEPARTMENTS ─────────────────────────────────────────────────────────
export const initialDepartments = [
  {
    id: 'D01',
    name: 'Computer Science',
    code: 'CS',
    building: 'Engineering Block',
    hod: 'Prof. S. Krishnamurthy',
    admin: 'Prof. Anitha Sharma'
  },
  {
    id: 'D02',
    name: 'Mechanical',
    code: 'MECH',
    building: 'Engineering Block',
    hod: 'Dr. P. Subramaniam',
    admin: 'Prof. Kavitha Raj'
  },
  {
    id: 'D03',
    name: 'Civil',
    code: 'CIVIL',
    building: 'Engineering Block',
    hod: 'Dr. Senthil Kumar',
    admin: 'Prof. Aruna Devi'
  },
  {
    id: 'D04',
    name: 'IT',
    code: 'IT',
    building: 'IT Block',
    hod: 'Dr. M. Venkatesh',
    admin: 'Prof. R. Revathi'
  },
  {
    id: 'D05',
    name: 'AIDS',
    code: 'AIDS',
    building: 'IT Block',
    hod: 'Dr. Nalini Patel',
    admin: 'Prof. K. Swaminathan'
  },
  {
    id: 'D06',
    name: 'ECE',
    code: 'ECE',
    building: 'Engineering Block',
    hod: 'Dr. S. Sundararajan',
    admin: 'Prof. Ramesh Nair'
  },
  {
    id: 'D07',
    name: 'EEE',
    code: 'EEE',
    building: 'Engineering Block',
    hod: 'Dr. R. Vijay Anand',
    admin: 'Prof. G. Murugan'
  },
  {
    id: 'D08',
    name: 'Science & Humanities',
    code: 'S&H',
    building: 'Science Block',
    hod: 'Dr. Lalitha Devi',
    admin: 'Prof. Dinesh Kumar'
  },
  {
    id: 'D09',
    name: 'Admin Block',
    code: 'ADM',
    building: 'Admin Block',
    hod: 'Dr. Rajesh Kumar',
    admin: 'Ms. Priya Mehta'
  }
];

// ─── 6. BUILDINGS ───────────────────────────────────────────────────────────
export const initialBuildings = [
  { id: 'B01', name: 'Engineering Block', code: 'ENG', floors: 4 },
  { id: 'B02', name: 'Science Block', code: 'SCI', floors: 3 },
  { id: 'B03', name: 'Admin Block', code: 'ADM', floors: 2 },
  { id: 'B04', name: 'IT Block', code: 'ITB', floors: 4 },
  { id: 'B05', name: 'Central Library', code: 'LIB', floors: 3 }
];

// ─── 7. ROOMS ───────────────────────────────────────────────────────────────
export const initialRooms = [
  {
    id: 'R01',
    number: 'CS-101',
    building: 'Engineering Block',
    department: 'Computer Science',
    floor: 1,
    type: 'Smart Classroom',
    capacity: 60
  },
  {
    id: 'R02',
    number: 'CS-Lab1',
    building: 'Engineering Block',
    department: 'Computer Science',
    floor: 2,
    type: 'Computer Laboratory',
    capacity: 40
  },
  {
    id: 'R03',
    number: 'MECH-101',
    building: 'Engineering Block',
    department: 'Mechanical',
    floor: 1,
    type: 'Lecture Hall',
    capacity: 60
  },
  {
    id: 'R04',
    number: 'MECH-Workshop',
    building: 'Engineering Block',
    department: 'Mechanical',
    floor: 1,
    type: 'Central Machine & CNC Workshop',
    capacity: 50
  },
  {
    id: 'R05',
    number: 'CIVIL-101',
    building: 'Engineering Block',
    department: 'Civil',
    floor: 1,
    type: 'Architectural Drafting Studio',
    capacity: 45
  },
  {
    id: 'R06',
    number: 'CIVIL-Lab1',
    building: 'Engineering Block',
    department: 'Civil',
    floor: 1,
    type: 'Materials & Concrete Testing Lab',
    capacity: 35
  },
  {
    id: 'R07',
    number: 'IT-101',
    building: 'IT Block',
    department: 'IT',
    floor: 1,
    type: 'Software Development Lab',
    capacity: 40
  },
  {
    id: 'R08',
    number: 'AIDS-101',
    building: 'IT Block',
    department: 'AIDS',
    floor: 2,
    type: 'AI & Deep Learning Computing Lab',
    capacity: 35
  },
  {
    id: 'R09',
    number: 'ECE-101',
    building: 'Engineering Block',
    department: 'ECE',
    floor: 3,
    type: 'VLSI & Embedded Systems Lab',
    capacity: 35
  },
  {
    id: 'R10',
    number: 'EEE-101',
    building: 'Engineering Block',
    department: 'EEE',
    floor: 2,
    type: 'Power Electronics & Drives Lab',
    capacity: 35
  },
  {
    id: 'R11',
    number: 'SH-101',
    building: 'Science Block',
    department: 'Science & Humanities',
    floor: 1,
    type: 'Foundational Sciences Smart Hall',
    capacity: 60
  },
  {
    id: 'R12',
    number: 'SH-PhysicsLab',
    building: 'Science Block',
    department: 'Science & Humanities',
    floor: 2,
    type: 'General Physics & Optics Lab',
    capacity: 40
  },
  {
    id: 'R13',
    number: 'SH-ChemistryLab',
    building: 'Science Block',
    department: 'Science & Humanities',
    floor: 3,
    type: 'Engineering Chemistry Lab',
    capacity: 40
  },
  {
    id: 'R14',
    number: 'ADM-101',
    building: 'Admin Block',
    department: 'Admin Block',
    floor: 1,
    type: 'Principal & Executive Administrative Office',
    capacity: 25
  },
  {
    id: 'R15',
    number: 'ADM-Hall',
    building: 'Admin Block',
    department: 'Admin Block',
    floor: 1,
    type: 'Main Boardroom & Senate Conference Hall',
    capacity: 40
  },
  {
    id: 'R16',
    number: 'ADM-Records',
    building: 'Admin Block',
    department: 'Admin Block',
    floor: 2,
    type: 'Confidential Examination & Records Vault',
    capacity: 15
  },
  {
    id: 'R17',
    number: 'ADM-ServerRoom',
    building: 'Admin Block',
    department: 'Admin Block',
    floor: 2,
    type: 'Campus Central Data Center & Server Room',
    capacity: 10
  }
];

// ─── 8. MAINTENANCE LOGS ────────────────────────────────────────────────────
export const initialMaintenanceLogs = [
  {
    id: 'MNT-001',
    assetId: 'AST-010',
    furniture: 'Optoma Projector System',
    issueDescription: 'Lamp dimming below acceptable lumens threshold during presentations',
    scheduledDate: '2026-09-15',
    completedDate: '2026-09-16',
    cost: 3500.00,
    status: 'Scheduled',
    vendor: 'Apex AV Solutions',
    technicianNotes: 'OEM replacement lamp scheduled for delivery and on-site testing'
  },
  {
    id: 'MNT-002',
    assetId: 'AST-096',
    furniture: 'Ricoh High-Capacity Multifunction Photocopier',
    issueDescription: 'Paper feed tray roller gear slipping under heavy print loads',
    scheduledDate: '2026-09-02',
    completedDate: '2026-09-07',
    cost: 4200.00,
    status: 'Completed',
    vendor: 'Matrix Electronics Care',
    technicianNotes: 'Replaced primary pick-up roller and aligned ADF scanning unit'
  },
  {
    id: 'MNT-003',
    assetId: 'AST-001',
    furniture: 'Dell OptiPlex 7090 Desktop Computer',
    issueDescription: 'Power supply unit fan noise during high compute load',
    scheduledDate: '2026-09-10',
    completedDate: '2026-09-11',
    cost: 1200.00,
    status: 'In Progress',
    vendor: 'Dell India Enterprise',
    technicianNotes: 'Dell gold warranty engineer dispatched for replacement unit'
  },
  {
    id: 'MNT-004',
    assetId: 'AST-095',
    furniture: 'Executive Conference Oval Table',
    issueDescription: 'Cable routing grommet loose on center conference desk',
    scheduledDate: '2026-08-20',
    completedDate: '2026-08-22',
    cost: 850.00,
    status: 'Completed',
    vendor: 'Godrej Interio Care',
    technicianNotes: 'Secured motorized popup power sockets and re-tightened brackets'
  },
  {
    id: 'MNT-005',
    assetId: 'AST-098',
    furniture: 'Godrej Fire-Resistant Filing Cabinet',
    issueDescription: 'Central multi-lever lock cylinder lubrication required',
    scheduledDate: '2026-09-12',
    completedDate: '2026-09-13',
    cost: 650.00,
    status: 'Scheduled',
    vendor: 'Godrej Interio Care',
    technicianNotes: 'Annual preventive inspection and master key cylinder calibration'
  }
];

// ─── 9. DISPOSALS ───────────────────────────────────────────────────────────
export const initialDisposals = [
  {
    id: 'DSP-001',
    assetId: 'AST-OLD-01',
    furniture: 'Cathode Ray Tube Monitors (Batch of 8)',
    disposalDate: '2026-08-15',
    reason: 'Scrapped',
    resaleValue: 1200.00,
    approvedBy: 'Dr. Rajesh Kumar',
    notes: 'E-waste handed over to authorized certified recycling partner GreenTech E-Waste.'
  },
  {
    id: 'DSP-002',
    assetId: 'AST-OLD-02',
    furniture: 'Defective Wooden Classroom Benches (Batch of 12)',
    disposalDate: '2026-08-28',
    reason: 'Damaged Beyond Repair',
    resaleValue: 3500.00,
    approvedBy: 'Dr. Rajesh Kumar',
    notes: 'Termite infestation and structural integrity failure. Sold to registered salvage auctioneer.'
  },
  {
    id: 'DSP-003',
    assetId: 'AST-OLD-03',
    furniture: 'Core2Duo Intel Desktops (Batch of 5)',
    disposalDate: '2026-09-01',
    reason: 'Donated',
    resaleValue: 0.00,
    approvedBy: 'Dr. Rajesh Kumar',
    notes: 'Donated to Rural High School Computer Literacy Program with hard drives securely wiped.'
  }
];

// ─── 10. VENDORS ────────────────────────────────────────────────────────────
export const initialVendors = [
  {
    id: 'VND-001',
    name: 'Apex AV Solutions',
    contactPerson: 'Arun Varma',
    email: 'sales@apexav.com',
    phone: '+91 98765 43210',
    address: 'Tech Park Zone, Phase 1, Bangalore, Karnataka',
    gstin: '29ABCDE1234F1Z5',
    rating: 4.8,
    services: 'Audio-Visual, Smart Interactive Boards, Laser Projectors, Sound Systems'
  },
  {
    id: 'VND-002',
    name: 'ErgoDesign Workspaces',
    contactPerson: 'Sunita Rao',
    email: 'support@ergodesign.in',
    phone: '+91 98111 22334',
    address: 'Industrial Area Phase 2, Guindy, Chennai, Tamil Nadu',
    gstin: '33ABCDE5678G2Z1',
    rating: 4.6,
    services: 'Modular Desks, Ergonomic Chairs, Laboratory Benches, Partitions'
  },
  {
    id: 'VND-003',
    name: 'Matrix Electronics Care',
    contactPerson: 'Karan Malhotra',
    email: 'service@matrixcare.co.in',
    phone: '+91 94444 88899',
    address: 'Electronics City, Hitec City, Hyderabad, Telangana',
    gstin: '36ABCDE9876H3Z8',
    rating: 4.5,
    services: 'Annual Maintenance Contracts (AMC), Motherboard Repair, Power Equipment'
  },
  {
    id: 'VND-004',
    name: 'Godrej Interio Commercial',
    contactPerson: 'Manoj Pillai',
    email: 'commercial@godrejinterio.com',
    phone: '+91 98222 33445',
    address: 'Express Towers, Nariman Point, Mumbai, Maharashtra',
    gstin: '27AAACG0563G1ZT',
    rating: 4.9,
    services: 'Heavy Duty Steel Cupboards, Classroom Dual Desks, Fireproof Safes'
  },
  {
    id: 'VND-005',
    name: 'Dell India Enterprise',
    contactPerson: 'Vikram Malhotra',
    email: 'enterprise_sales@dell.com',
    phone: '+91 80 4123 5500',
    address: 'Divyasree Greens, Koramangala, Bangalore, Karnataka',
    gstin: '29AAACD0125F1Z8',
    rating: 4.7,
    services: 'Workstations, High-Performance Rack Servers, LED Monitors, Networking'
  },
  {
    id: 'VND-006',
    name: 'ThermoFisher Scientific Lab Solutions',
    contactPerson: 'Dr. S. Ramesh',
    email: 'instruments.in@thermofisher.com',
    phone: '+91 22 6716 2200',
    address: 'Powai Business Park, Andheri East, Mumbai, Maharashtra',
    gstin: '27AAACT1948B1Z0',
    rating: 4.9,
    services: 'Digital Precision Balances, Spectrophotometers, Microscopes, Lab Autoclaves'
  },
  {
    id: 'VND-007',
    name: 'Cisco Networks & IT Infrastructure',
    contactPerson: 'Aditi Sengupta',
    email: 'apac_sales@cisco-partner.in',
    phone: '+91 80 4426 1000',
    address: 'Prestige Tech Park, Marathahalli-Sarjapur Ring Rd, Bangalore, Karnataka',
    gstin: '29AAACC3388L1ZQ',
    rating: 4.8,
    services: 'Managed Gigabit PoE Switches, Wi-Fi 6 Access Points, Enterprise Firewalls'
  }
];

// ─── 11. AUDIT LOGS ─────────────────────────────────────────────────────────
export const initialAuditLogs = [
  {
    id: 'AUD-001',
    userId: 'USR-001',
    userName: 'Dr. Rajesh Kumar',
    userRole: 'superadmin',
    action: 'CREATE',
    entity: 'Asset',
    entityId: 'AST-092',
    details: 'Registered Admin Workstation Dell Precision 3660 for central institutional records',
    created_at: '2026-09-01T09:30:00.000Z'
  },
  {
    id: 'AUD-002',
    userId: 'USR-002',
    userName: 'Prof. Anitha Sharma',
    userRole: 'deptadmin',
    action: 'TRANSFER',
    entity: 'Asset',
    entityId: 'AST-010',
    details: 'Transferred Projector System from CS-101 to CS-102 for online webinar series',
    created_at: '2026-09-02T11:15:00.000Z'
  },
  {
    id: 'AUD-003',
    userId: 'USR-011',
    userName: 'Mr. Ravi Shankar',
    userRole: 'auditor',
    action: 'INSPECT',
    entity: 'Asset',
    entityId: 'AST-096',
    details: 'Logged physical inspection: Ricoh High-Capacity Multifunction Photocopier verified',
    created_at: '2026-09-03T14:20:00.000Z'
  },
  {
    id: 'AUD-004',
    userId: 'USR-001',
    userName: 'Dr. Rajesh Kumar',
    userRole: 'superadmin',
    action: 'DISPOSE',
    entity: 'Asset',
    entityId: 'AST-OLD-01',
    details: 'Approved disposal and e-waste recycling of 8 CRT monitors with resale recovery of ₹1,200',
    created_at: '2026-09-04T16:45:00.000Z'
  },
  {
    id: 'AUD-005',
    userId: 'USR-007',
    userName: 'Prof. Ramesh Nair',
    userRole: 'deptadmin',
    action: 'UPDATE',
    entity: 'Asset',
    entityId: 'AST-065',
    details: 'Updated custodian assignment for FPGA Development Trainer Board in ECE Lab 2',
    created_at: '2026-09-05T10:05:00.000Z'
  },
  {
    id: 'AUD-006',
    userId: 'USR-001',
    userName: 'Dr. Rajesh Kumar',
    userRole: 'superadmin',
    action: 'CREATE',
    entity: 'Vendor',
    entityId: 'VND-005',
    details: 'Added Dell India Enterprise to approved campus hardware supplier directory',
    created_at: '2026-09-06T13:00:00.000Z'
  }
];

// ─── 12. CATEGORIES ─────────────────────────────────────────────────────────
export const initialCategories = [
  {
    id: 'CAT-001',
    name: 'Chairs & Seating',
    mainCategory: 'Furniture',
    code: 'CHR',
    icon: 'Chair',
    depreciationRate: 15.00,
    usefulLifeYears: 7,
    description: 'Task chairs, executive chairs, conference chairs, and lab stools'
  },
  {
    id: 'CAT-002',
    name: 'Desks & Tables',
    mainCategory: 'Furniture',
    code: 'DSK',
    icon: 'Table',
    depreciationRate: 10.00,
    usefulLifeYears: 10,
    description: 'Faculty desks, student benches, podiums, conference tables'
  },
  {
    id: 'CAT-003',
    name: 'Display & Boards',
    mainCategory: 'Furniture',
    code: 'BRD',
    icon: 'Tv',
    depreciationRate: 12.50,
    usefulLifeYears: 8,
    description: 'Magnetic whiteboards, interactive smart boards, and pin-up notice boards'
  },
  {
    id: 'CAT-004',
    name: 'AV & Electronic Equipment',
    mainCategory: 'Electronics',
    code: 'AVE',
    icon: 'Monitor',
    depreciationRate: 20.00,
    usefulLifeYears: 5,
    description: 'Laser projectors, digital smart boards, sound systems, presentation gear'
  },
  {
    id: 'CAT-005',
    name: 'Storage & Cupboards',
    mainCategory: 'Furniture',
    code: 'STR',
    icon: 'Archive',
    depreciationRate: 10.00,
    usefulLifeYears: 12,
    description: 'Heavy-gauge steel almirahs, filing cabinets, library book racks'
  },
  {
    id: 'CAT-006',
    name: 'Laboratory Equipment & Benches',
    mainCategory: 'Laboratory',
    code: 'LAB',
    icon: 'FlaskConical',
    depreciationRate: 15.00,
    usefulLifeYears: 8,
    description: 'Acid-resistant granite tables, fume hoods, electronic test benches'
  }
];

// ─── 13. PURCHASE HISTORY & PRICE TRACKING RECORDS ──────────────────────────
export const initialPurchaseHistory = [
  {
    id: 'PUR-2024-001',
    assetId: 'AST-001',
    assetName: 'Ergonomic High-Back Mesh Task Chair',
    vendorId: 'VND-002',
    vendorName: 'ErgoDesign Workspaces',
    categoryId: 'CAT-001',
    categoryName: 'Furniture',
    subcategoryId: 'SUB-CHR',
    subcategoryName: 'Chair',
    itemType: 'Task Chair',
    purchaseDate: '2024-06-15',
    purchasePrice: 7200.00,
    quantity: 20,
    totalAmount: 144000.00,
    invoiceNumber: 'INV-ED-2024-88',
    invoiceDate: '2024-06-12',
    warrantyExpiry: '2027-06-15 (3 Years)',
    notes: 'Batch procurement for CSE Computing Lab 1.'
  },
  {
    id: 'PUR-2025-002',
    assetId: 'AST-001',
    assetName: 'Ergonomic High-Back Mesh Task Chair',
    vendorId: 'VND-002',
    vendorName: 'ErgoDesign Workspaces',
    categoryId: 'CAT-001',
    categoryName: 'Furniture',
    subcategoryId: 'SUB-CHR',
    subcategoryName: 'Chair',
    itemType: 'Task Chair',
    purchaseDate: '2025-02-10',
    purchasePrice: 7500.00,
    quantity: 15,
    totalAmount: 112500.00,
    invoiceNumber: 'INV-ED-2025-102',
    invoiceDate: '2025-02-08',
    warrantyExpiry: '2028-02-10 (3 Years)',
    notes: 'Replenishment batch for AI Research Lab.'
  },
  {
    id: 'PUR-2026-003',
    assetId: 'AST-001',
    assetName: 'Ergonomic High-Back Mesh Task Chair',
    vendorId: 'VND-002',
    vendorName: 'ErgoDesign Workspaces',
    categoryId: 'CAT-001',
    categoryName: 'Furniture',
    subcategoryId: 'SUB-CHR',
    subcategoryName: 'Chair',
    itemType: 'Task Chair',
    purchaseDate: '2026-01-15',
    purchasePrice: 7800.00,
    quantity: 5,
    totalAmount: 39000.00,
    invoiceNumber: 'INV-ED-2026-019',
    invoiceDate: '2026-01-14',
    warrantyExpiry: '2029-01-15 (3 Years)',
    notes: 'Additional units for HOD meeting room.'
  },
  {
    id: 'PUR-2024-004',
    assetId: 'AST-002',
    assetName: 'Student Chair with Wooden Writing Pad',
    vendorId: 'VND-004',
    vendorName: 'Godrej Interio Commercial',
    categoryId: 'CAT-001',
    categoryName: 'Furniture',
    subcategoryId: 'SUB-CHR',
    subcategoryName: 'Chair',
    itemType: 'Student Chair with Writing Pad',
    purchaseDate: '2024-08-20',
    purchasePrice: 2900.00,
    quantity: 30,
    totalAmount: 87000.00,
    invoiceNumber: 'INV-GI-9921',
    invoiceDate: '2024-08-18',
    warrantyExpiry: '2027-08-20 (3 Years)',
    notes: 'First year engineering lecture hall setup.'
  },
  {
    id: 'PUR-2025-005',
    assetId: 'AST-002',
    assetName: 'Student Chair with Wooden Writing Pad',
    vendorId: 'VND-004',
    vendorName: 'Godrej Interio Commercial',
    categoryId: 'CAT-001',
    categoryName: 'Furniture',
    subcategoryId: 'SUB-CHR',
    subcategoryName: 'Chair',
    itemType: 'Student Chair with Writing Pad',
    purchaseDate: '2025-07-12',
    purchasePrice: 3100.00,
    quantity: 20,
    totalAmount: 62000.00,
    invoiceNumber: 'INV-GI-1142',
    invoiceDate: '2025-07-10',
    warrantyExpiry: '2028-07-12 (3 Years)',
    notes: 'Lecture hall CS-101 replacement quota.'
  },
  {
    id: 'PUR-2026-006',
    assetId: 'AST-002',
    assetName: 'Student Chair with Wooden Writing Pad',
    vendorId: 'VND-004',
    vendorName: 'Godrej Interio Commercial',
    categoryId: 'CAT-001',
    categoryName: 'Furniture',
    subcategoryId: 'SUB-CHR',
    subcategoryName: 'Chair',
    itemType: 'Student Chair with Writing Pad',
    purchaseDate: '2026-02-05',
    purchasePrice: 3200.00,
    quantity: 10,
    totalAmount: 32000.00,
    invoiceNumber: 'INV-GI-2034',
    invoiceDate: '2026-02-02',
    warrantyExpiry: '2029-02-05 (3 Years)',
    notes: 'Supplementary student seating.'
  },
  {
    id: 'PUR-2024-007',
    assetId: 'AST-003',
    assetName: 'Moulded Polypropylene Student Chair',
    vendorId: 'VND-002',
    vendorName: 'ErgoDesign Workspaces',
    categoryId: 'CAT-001',
    categoryName: 'Furniture',
    subcategoryId: 'SUB-CHR',
    subcategoryName: 'Chair',
    itemType: 'Student Chair',
    purchaseDate: '2024-05-18',
    purchasePrice: 1750.00,
    quantity: 40,
    totalAmount: 70000.00,
    invoiceNumber: 'INV-ED-5421',
    invoiceDate: '2024-05-15',
    warrantyExpiry: '2026-05-18 (2 Years)',
    notes: 'Mechanical dept drawing hall seating.'
  },
  {
    id: 'PUR-2025-008',
    assetId: 'AST-003',
    assetName: 'Moulded Polypropylene Student Chair',
    vendorId: 'VND-004',
    vendorName: 'Godrej Interio Commercial',
    categoryId: 'CAT-001',
    categoryName: 'Furniture',
    subcategoryId: 'SUB-CHR',
    subcategoryName: 'Chair',
    itemType: 'Student Chair',
    purchaseDate: '2025-06-25',
    purchasePrice: 1850.00,
    quantity: 25,
    totalAmount: 46250.00,
    invoiceNumber: 'INV-GI-8831',
    invoiceDate: '2025-06-22',
    warrantyExpiry: '2027-06-25 (2 Years)',
    notes: 'Classroom ME-101 additional order.'
  },
  {
    id: 'PUR-2024-009',
    assetId: 'AST-004',
    assetName: 'Executive High-Back Leatherette Faculty Chair',
    vendorId: 'VND-002',
    vendorName: 'ErgoDesign Workspaces',
    categoryId: 'CAT-001',
    categoryName: 'Furniture',
    subcategoryId: 'SUB-CHR',
    subcategoryName: 'Chair',
    itemType: 'Faculty Chair',
    purchaseDate: '2024-11-10',
    purchasePrice: 14000.00,
    quantity: 2,
    totalAmount: 28000.00,
    invoiceNumber: 'INV-ED-9002',
    invoiceDate: '2024-11-08',
    warrantyExpiry: '2027-11-10 (3 Years)',
    notes: 'Principal & Vice Principal chambers.'
  },
  {
    id: 'PUR-2025-010',
    assetId: 'AST-004',
    assetName: 'Executive High-Back Leatherette Faculty Chair',
    vendorId: 'VND-002',
    vendorName: 'ErgoDesign Workspaces',
    categoryId: 'CAT-001',
    categoryName: 'Furniture',
    subcategoryId: 'SUB-CHR',
    subcategoryName: 'Chair',
    itemType: 'Faculty Chair',
    purchaseDate: '2025-10-15',
    purchasePrice: 15500.00,
    quantity: 4,
    totalAmount: 62000.00,
    invoiceNumber: 'INV-ED-9421',
    invoiceDate: '2025-10-12',
    warrantyExpiry: '2028-10-15 (3 Years)',
    notes: 'Senior Professor cabins in Admin Block.'
  },
  {
    id: 'PUR-2024-011',
    assetId: 'AST-007',
    assetName: 'Granite Top 3-Person Student Chemistry Lab Table',
    vendorId: 'VND-002',
    vendorName: 'ErgoDesign Workspaces',
    categoryId: 'CAT-002',
    categoryName: 'Furniture',
    subcategoryId: 'SUB-TBL',
    subcategoryName: 'Table',
    itemType: 'Student Table',
    purchaseDate: '2024-04-12',
    purchasePrice: 26000.00,
    quantity: 6,
    totalAmount: 156000.00,
    invoiceNumber: 'INV-ED-3341',
    invoiceDate: '2024-04-10',
    warrantyExpiry: '2029-04-12 (5 Years)',
    notes: 'Chemistry Laboratory Phase 1 renovation.'
  },
  {
    id: 'PUR-2025-012',
    assetId: 'AST-007',
    assetName: 'Granite Top 3-Person Student Chemistry Lab Table',
    vendorId: 'VND-002',
    vendorName: 'ErgoDesign Workspaces',
    categoryId: 'CAT-002',
    categoryName: 'Furniture',
    subcategoryId: 'SUB-TBL',
    subcategoryName: 'Table',
    itemType: 'Student Table',
    purchaseDate: '2025-11-20',
    purchasePrice: 28500.00,
    quantity: 6,
    totalAmount: 171000.00,
    invoiceNumber: 'INV-ED-7821',
    invoiceDate: '2025-11-18',
    warrantyExpiry: '2030-11-20 (5 Years)',
    notes: 'Chemistry Laboratory Phase 2 expansion.'
  },
  {
    id: 'PUR-2025-013',
    assetId: 'AST-009',
    assetName: 'Executive Teak Wood Faculty Work Desk',
    vendorId: 'VND-004',
    vendorName: 'Godrej Interio Commercial',
    categoryId: 'CAT-002',
    categoryName: 'Furniture',
    subcategoryId: 'SUB-TBL',
    subcategoryName: 'Table',
    itemType: 'Faculty Table',
    purchaseDate: '2025-01-20',
    purchasePrice: 21000.00,
    quantity: 2,
    totalAmount: 42000.00,
    invoiceNumber: 'INV-GI-3921',
    invoiceDate: '2025-01-18',
    warrantyExpiry: '2030-01-20 (5 Years)',
    notes: 'ECE Department Professor desks.'
  },
  {
    id: 'PUR-2026-014',
    assetId: 'AST-009',
    assetName: 'Executive Teak Wood Faculty Work Desk',
    vendorId: 'VND-004',
    vendorName: 'Godrej Interio Commercial',
    categoryId: 'CAT-002',
    categoryName: 'Furniture',
    subcategoryId: 'SUB-TBL',
    subcategoryName: 'Table',
    itemType: 'Faculty Table',
    purchaseDate: '2026-01-10',
    purchasePrice: 22500.00,
    quantity: 2,
    totalAmount: 45000.00,
    invoiceNumber: 'INV-GI-5011',
    invoiceDate: '2026-01-08',
    warrantyExpiry: '2031-01-10 (5 Years)',
    notes: 'ECE Lab 2 Faculty workstations.'
  },
  {
    id: 'PUR-2024-015',
    assetId: 'AST-015',
    assetName: 'High-Lumen 4K Laser Classroom Projector',
    vendorId: 'VND-001',
    vendorName: 'Apex AV Solutions',
    categoryId: 'CAT-004',
    categoryName: 'Electronics',
    subcategoryId: 'SUB-PRJ',
    subcategoryName: 'Projector',
    itemType: 'Laser Projector',
    purchaseDate: '2024-09-15',
    purchasePrice: 82000.00,
    quantity: 2,
    totalAmount: 164000.00,
    invoiceNumber: 'INV-AV-2024-71',
    invoiceDate: '2024-09-12',
    warrantyExpiry: '2027-09-15 (3 Years Onsite)',
    notes: 'Smart Seminar Hall 1 & 2 installation.'
  },
  {
    id: 'PUR-2025-016',
    assetId: 'AST-015',
    assetName: 'High-Lumen 4K Laser Classroom Projector',
    vendorId: 'VND-001',
    vendorName: 'Apex AV Solutions',
    categoryId: 'CAT-004',
    categoryName: 'Electronics',
    subcategoryId: 'SUB-PRJ',
    subcategoryName: 'Projector',
    itemType: 'Laser Projector',
    purchaseDate: '2025-08-10',
    purchasePrice: 85000.00,
    quantity: 4,
    totalAmount: 340000.00,
    invoiceNumber: 'INV-AV-2025-19',
    invoiceDate: '2025-08-08',
    warrantyExpiry: '2028-08-10 (3 Years Onsite)',
    notes: 'Multimedia classrooms upgrade batch.'
  },
  {
    id: 'PUR-2026-017',
    assetId: 'AST-015',
    assetName: 'High-Lumen 4K Laser Classroom Projector',
    vendorId: 'VND-001',
    vendorName: 'Apex AV Solutions',
    categoryId: 'CAT-004',
    categoryName: 'Electronics',
    subcategoryId: 'SUB-PRJ',
    subcategoryName: 'Projector',
    itemType: 'Laser Projector',
    purchaseDate: '2026-03-01',
    purchasePrice: 88000.00,
    quantity: 2,
    totalAmount: 176000.00,
    invoiceNumber: 'INV-AV-2026-04',
    invoiceDate: '2026-02-27',
    warrantyExpiry: '2029-03-01 (3 Years Onsite)',
    notes: 'Auditorium supplementary projection system.'
  },
  {
    id: 'PUR-2025-018',
    assetId: 'AST-016',
    assetName: 'Interactive Multi-Touch Smart Whiteboard',
    vendorId: 'VND-001',
    vendorName: 'Apex AV Solutions',
    categoryId: 'CAT-003',
    categoryName: 'Furniture',
    subcategoryId: 'SUB-BRD',
    subcategoryName: 'Boards',
    itemType: 'Interactive Smart Board',
    purchaseDate: '2025-03-10',
    purchasePrice: 115000.00,
    quantity: 3,
    totalAmount: 345000.00,
    invoiceNumber: 'INV-AV-2025-33',
    invoiceDate: '2025-03-08',
    warrantyExpiry: '2028-03-10 (3 Years)',
    notes: 'Smart classroom interactive teaching boards.'
  },
  {
    id: 'PUR-2026-019',
    assetId: 'AST-016',
    assetName: 'Interactive Multi-Touch Smart Whiteboard',
    vendorId: 'VND-001',
    vendorName: 'Apex AV Solutions',
    categoryId: 'CAT-003',
    categoryName: 'Furniture',
    subcategoryId: 'SUB-BRD',
    subcategoryName: 'Boards',
    itemType: 'Interactive Smart Board',
    purchaseDate: '2026-02-18',
    purchasePrice: 122000.00,
    quantity: 2,
    totalAmount: 244000.00,
    invoiceNumber: 'INV-AV-2026-12',
    invoiceDate: '2026-02-15',
    warrantyExpiry: '2029-02-18 (3 Years)',
    notes: 'Virtual classroom 3 & 4 additions.'
  },
  {
    id: 'PUR-2024-020',
    assetId: 'AST-020',
    assetName: 'Dell OptiPlex Desktop Workstation',
    vendorId: 'VND-005',
    vendorName: 'Dell India Enterprise',
    categoryId: 'CAT-004',
    categoryName: 'Electronics',
    subcategoryId: 'SUB-CMP',
    subcategoryName: 'Computer',
    itemType: 'Desktop Workstation',
    purchaseDate: '2024-07-10',
    purchasePrice: 58000.00,
    quantity: 15,
    totalAmount: 870000.00,
    invoiceNumber: 'INV-DELL-2024-101',
    invoiceDate: '2024-07-08',
    warrantyExpiry: '2027-07-10 (3 Years ProSupport)',
    notes: 'Initial purchase for CSE Data Science Lab.'
  },
  {
    id: 'PUR-2025-021',
    assetId: 'AST-020',
    assetName: 'Dell OptiPlex Desktop Workstation',
    vendorId: 'VND-005',
    vendorName: 'Dell India Enterprise',
    categoryId: 'CAT-004',
    categoryName: 'Electronics',
    subcategoryId: 'SUB-CMP',
    subcategoryName: 'Computer',
    itemType: 'Desktop Workstation',
    purchaseDate: '2025-03-15',
    purchasePrice: 62000.00,
    quantity: 15,
    totalAmount: 930000.00,
    invoiceNumber: 'INV-DELL-2025-045',
    invoiceDate: '2025-03-12',
    warrantyExpiry: '2028-03-15 (3 Years ProSupport)',
    notes: 'Batch 2 order with updated 13th Gen Intel processors.'
  },
  {
    id: 'PUR-2026-022',
    assetId: 'AST-020',
    assetName: 'Dell OptiPlex Desktop Workstation',
    vendorId: 'VND-005',
    vendorName: 'Dell India Enterprise',
    categoryId: 'CAT-004',
    categoryName: 'Electronics',
    subcategoryId: 'SUB-CMP',
    subcategoryName: 'Computer',
    itemType: 'Desktop Workstation',
    purchaseDate: '2026-01-20',
    purchasePrice: 65000.00,
    quantity: 10,
    totalAmount: 650000.00,
    invoiceNumber: 'INV-DELL-2026-009',
    invoiceDate: '2026-01-18',
    warrantyExpiry: '2029-01-20 (3 Years ProSupport)',
    notes: 'Latest purchase with 32GB RAM upgrade.'
  },
  {
    id: 'PUR-2025-023',
    assetId: 'AST-021',
    assetName: 'Dell Latitude Core i7 Faculty Laptop',
    vendorId: 'VND-005',
    vendorName: 'Dell India Enterprise',
    categoryId: 'CAT-004',
    categoryName: 'Electronics',
    subcategoryId: 'SUB-CMP',
    subcategoryName: 'Computer',
    itemType: 'Laptop',
    purchaseDate: '2025-02-14',
    purchasePrice: 72000.00,
    quantity: 5,
    totalAmount: 360000.00,
    invoiceNumber: 'INV-DELL-2025-022',
    invoiceDate: '2025-02-12',
    warrantyExpiry: '2028-02-14 (3 Years Complete Care)',
    notes: 'Issued to Department Heads for academic administration.'
  },
  {
    id: 'PUR-2026-024',
    assetId: 'AST-021',
    assetName: 'Dell Latitude Core i7 Faculty Laptop',
    vendorId: 'VND-005',
    vendorName: 'Dell India Enterprise',
    categoryId: 'CAT-004',
    categoryName: 'Electronics',
    subcategoryId: 'SUB-CMP',
    subcategoryName: 'Computer',
    itemType: 'Laptop',
    purchaseDate: '2026-02-10',
    purchasePrice: 76500.00,
    quantity: 5,
    totalAmount: 382500.00,
    invoiceNumber: 'INV-DELL-2026-015',
    invoiceDate: '2026-02-08',
    warrantyExpiry: '2029-02-10 (3 Years Complete Care)',
    notes: 'Issued to newly joined senior faculty members.'
  },
  {
    id: 'PUR-2025-025',
    assetId: 'AST-022',
    assetName: 'Matrix Smart UPS & Power Backup 5KVA',
    vendorId: 'VND-003',
    vendorName: 'Matrix Electronics Care',
    categoryId: 'CAT-004',
    categoryName: 'Electronics',
    subcategoryId: 'SUB-PWR',
    subcategoryName: 'Power & UPS',
    itemType: 'Online UPS',
    purchaseDate: '2025-04-18',
    purchasePrice: 44000.00,
    quantity: 4,
    totalAmount: 176000.00,
    invoiceNumber: 'INV-MTR-8812',
    invoiceDate: '2025-04-15',
    warrantyExpiry: '2027-04-18 (2 Years Battery + Inverter)',
    notes: 'Power backup for CSE Server Room and IoT Lab.'
  },
  {
    id: 'PUR-2026-026',
    assetId: 'AST-022',
    assetName: 'Matrix Smart UPS & Power Backup 5KVA',
    vendorId: 'VND-003',
    vendorName: 'Matrix Electronics Care',
    categoryId: 'CAT-004',
    categoryName: 'Electronics',
    subcategoryId: 'SUB-PWR',
    subcategoryName: 'Power & UPS',
    itemType: 'Online UPS',
    purchaseDate: '2026-02-28',
    purchasePrice: 46500.00,
    quantity: 2,
    totalAmount: 93000.00,
    invoiceNumber: 'INV-MTR-9901',
    invoiceDate: '2026-02-25',
    warrantyExpiry: '2028-02-28 (2 Years Battery + Inverter)',
    notes: 'Power backup for AI & Data Science Server Rack.'
  },
  // Laboratory Purchases
  {
    id: 'PUR-2024-027',
    assetId: 'AST-101',
    assetName: 'Digital Precision Electronic Analytical Laboratory Balance 0.1mg',
    vendorId: 'VND-006',
    vendorName: 'ThermoFisher Scientific Lab Solutions',
    categoryId: 'CAT-LAB',
    categoryName: 'Laboratory',
    subcategoryId: 'SUB-ANA',
    subcategoryName: 'Analytical Instruments',
    itemType: 'Digital Precision Analytical Balance',
    purchaseDate: '2024-04-12',
    purchasePrice: 42000.00,
    quantity: 4,
    totalAmount: 168000.00,
    invoiceNumber: 'INV-TF-2024-104',
    invoiceDate: '2024-04-10',
    warrantyExpiry: '2027-04-12 (3 Years Calibration)',
    notes: 'Procured for Science & Humanities Chemistry Advanced Testing Lab.'
  },
  {
    id: 'PUR-2025-028',
    assetId: 'AST-101',
    assetName: 'Digital Precision Electronic Analytical Laboratory Balance 0.1mg',
    vendorId: 'VND-006',
    vendorName: 'ThermoFisher Scientific Lab Solutions',
    categoryId: 'CAT-LAB',
    categoryName: 'Laboratory',
    subcategoryId: 'SUB-ANA',
    subcategoryName: 'Analytical Instruments',
    itemType: 'Digital Precision Analytical Balance',
    purchaseDate: '2025-03-18',
    purchasePrice: 44500.00,
    quantity: 6,
    totalAmount: 267000.00,
    invoiceNumber: 'INV-TF-2025-219',
    invoiceDate: '2025-03-15',
    warrantyExpiry: '2028-03-18 (3 Years Calibration)',
    notes: 'Batch addition for Biotechnology & Material Science Lab.'
  },
  {
    id: 'PUR-2026-029',
    assetId: 'AST-101',
    assetName: 'Digital Precision Electronic Analytical Laboratory Balance 0.1mg',
    vendorId: 'VND-006',
    vendorName: 'ThermoFisher Scientific Lab Solutions',
    categoryId: 'CAT-LAB',
    categoryName: 'Laboratory',
    subcategoryId: 'SUB-ANA',
    subcategoryName: 'Analytical Instruments',
    itemType: 'Digital Precision Analytical Balance',
    purchaseDate: '2026-01-22',
    purchasePrice: 46200.00,
    quantity: 3,
    totalAmount: 138600.00,
    invoiceNumber: 'INV-TF-2026-041',
    invoiceDate: '2026-01-20',
    warrantyExpiry: '2029-01-22 (3 Years Calibration)',
    notes: 'Replenishment for PG Nanotechnology Research Section.'
  },
  {
    id: 'PUR-2024-030',
    assetId: 'AST-102',
    assetName: 'Binocular Research Compound Microscope with LED Illumination',
    vendorId: 'VND-006',
    vendorName: 'ThermoFisher Scientific Lab Solutions',
    categoryId: 'CAT-LAB',
    categoryName: 'Laboratory',
    subcategoryId: 'SUB-OPT',
    subcategoryName: 'Optical & Microscopy',
    itemType: 'Binocular Research Compound Microscope',
    purchaseDate: '2024-07-15',
    purchasePrice: 18500.00,
    quantity: 10,
    totalAmount: 185000.00,
    invoiceNumber: 'INV-TF-2024-388',
    invoiceDate: '2024-07-12',
    warrantyExpiry: '2027-07-15 (3 Years Optics)',
    notes: 'First-year Biology & Microscopy practical hall installation.'
  },
  {
    id: 'PUR-2025-031',
    assetId: 'AST-102',
    assetName: 'Binocular Research Compound Microscope with LED Illumination',
    vendorId: 'VND-006',
    vendorName: 'ThermoFisher Scientific Lab Solutions',
    categoryId: 'CAT-LAB',
    categoryName: 'Laboratory',
    subcategoryId: 'SUB-OPT',
    subcategoryName: 'Optical & Microscopy',
    itemType: 'Binocular Research Compound Microscope',
    purchaseDate: '2025-06-20',
    purchasePrice: 19800.00,
    quantity: 15,
    totalAmount: 297000.00,
    invoiceNumber: 'INV-TF-2025-502',
    invoiceDate: '2025-06-18',
    warrantyExpiry: '2028-06-20 (3 Years Optics)',
    notes: 'Capacity expansion for Microbiology and Pathology practical lab.'
  },
  {
    id: 'PUR-2026-032',
    assetId: 'AST-102',
    assetName: 'Binocular Research Compound Microscope with LED Illumination',
    vendorId: 'VND-006',
    vendorName: 'ThermoFisher Scientific Lab Solutions',
    categoryId: 'CAT-LAB',
    categoryName: 'Laboratory',
    subcategoryId: 'SUB-OPT',
    subcategoryName: 'Optical & Microscopy',
    itemType: 'Binocular Research Compound Microscope',
    purchaseDate: '2026-02-14',
    purchasePrice: 21000.00,
    quantity: 8,
    totalAmount: 168000.00,
    invoiceNumber: 'INV-TF-2026-092',
    invoiceDate: '2026-02-11',
    warrantyExpiry: '2029-02-14 (3 Years Optics)',
    notes: 'Advanced high-magnification immersion oil units.'
  },
  {
    id: 'PUR-2024-033',
    assetId: 'AST-103',
    assetName: 'Horizontal Laminar Air Flow Chamber Ultra Clean Workstation',
    vendorId: 'VND-006',
    vendorName: 'ThermoFisher Scientific Lab Solutions',
    categoryId: 'CAT-LAB',
    categoryName: 'Laboratory',
    subcategoryId: 'SUB-BIO',
    subcategoryName: 'Glassware & Biosafety',
    itemType: 'Horizontal Laminar Air Flow Chamber',
    purchaseDate: '2024-09-05',
    purchasePrice: 78000.00,
    quantity: 2,
    totalAmount: 156000.00,
    invoiceNumber: 'INV-TF-2024-610',
    invoiceDate: '2024-09-02',
    warrantyExpiry: '2026-09-05 (2 Years HEPA & Motor)',
    notes: 'Sterile culture inoculation workstation for Tissue Culture Lab.'
  },
  {
    id: 'PUR-2025-034',
    assetId: 'AST-103',
    assetName: 'Horizontal Laminar Air Flow Chamber Ultra Clean Workstation',
    vendorId: 'VND-006',
    vendorName: 'ThermoFisher Scientific Lab Solutions',
    categoryId: 'CAT-LAB',
    categoryName: 'Laboratory',
    subcategoryId: 'SUB-BIO',
    subcategoryName: 'Glassware & Biosafety',
    itemType: 'Horizontal Laminar Air Flow Chamber',
    purchaseDate: '2025-08-12',
    purchasePrice: 82500.00,
    quantity: 3,
    totalAmount: 247500.00,
    invoiceNumber: 'INV-TF-2025-780',
    invoiceDate: '2025-08-10',
    warrantyExpiry: '2027-08-12 (2 Years HEPA & Motor)',
    notes: 'HEPA 99.99% certified bio-safety inoculation cabinets.'
  },
  {
    id: 'PUR-2024-035',
    assetId: 'AST-104',
    assetName: 'Pelton Wheel Turbine Fluid Mechanics Rig',
    vendorId: 'VND-006',
    vendorName: 'ThermoFisher Scientific Lab Solutions',
    categoryId: 'CAT-LAB',
    categoryName: 'Laboratory',
    subcategoryId: 'SUB-ENG',
    subcategoryName: 'Engineering & Testing',
    itemType: 'Pelton Wheel Turbine Fluid Mechanics Rig',
    purchaseDate: '2024-05-20',
    purchasePrice: 145000.00,
    quantity: 1,
    totalAmount: 145000.00,
    invoiceNumber: 'INV-TF-2024-245',
    invoiceDate: '2024-05-18',
    warrantyExpiry: '2027-05-20 (3 Years Comprehensive)',
    notes: 'Heavy engineering test apparatus for Mechanical Fluid Mechanics Lab.'
  },
  {
    id: 'PUR-2025-036',
    assetId: 'AST-104',
    assetName: 'Pelton Wheel Turbine Fluid Mechanics Rig',
    vendorId: 'VND-006',
    vendorName: 'ThermoFisher Scientific Lab Solutions',
    categoryId: 'CAT-LAB',
    categoryName: 'Laboratory',
    subcategoryId: 'SUB-ENG',
    subcategoryName: 'Engineering & Testing',
    itemType: 'Pelton Wheel Turbine Fluid Mechanics Rig',
    purchaseDate: '2025-10-15',
    purchasePrice: 152000.00,
    quantity: 1,
    totalAmount: 152000.00,
    invoiceNumber: 'INV-TF-2025-911',
    invoiceDate: '2025-10-12',
    warrantyExpiry: '2028-10-15 (3 Years Comprehensive)',
    notes: 'Second test bed unit for hydraulic power and efficiency experiments.'
  },
  // IT Hardware Purchases
  {
    id: 'PUR-2024-037',
    assetId: 'AST-201',
    assetName: 'All-in-One Desktop Core i7 Workstation (32GB RAM, 1TB SSD)',
    vendorId: 'VND-005',
    vendorName: 'Dell India Enterprise',
    categoryId: 'CAT-IT',
    categoryName: 'IT Hardware',
    subcategoryId: 'SUB-COM',
    subcategoryName: 'Computing & Workstations',
    itemType: 'All-in-One Desktop Core i7 Workstation',
    purchaseDate: '2024-03-25',
    purchasePrice: 68000.00,
    quantity: 25,
    totalAmount: 1700000.00,
    invoiceNumber: 'INV-DELL-2024-118',
    invoiceDate: '2024-03-22',
    warrantyExpiry: '2027-03-25 (3 Years ProSupport NBD)',
    notes: 'CSE Department Main Software Lab 1 infrastructure upgrade.'
  },
  {
    id: 'PUR-2025-038',
    assetId: 'AST-201',
    assetName: 'All-in-One Desktop Core i7 Workstation (32GB RAM, 1TB SSD)',
    vendorId: 'VND-005',
    vendorName: 'Dell India Enterprise',
    categoryId: 'CAT-IT',
    categoryName: 'IT Hardware',
    subcategoryId: 'SUB-COM',
    subcategoryName: 'Computing & Workstations',
    itemType: 'All-in-One Desktop Core i7 Workstation',
    purchaseDate: '2025-04-10',
    purchasePrice: 71500.00,
    quantity: 30,
    totalAmount: 2145000.00,
    invoiceNumber: 'INV-DELL-2025-410',
    invoiceDate: '2025-04-08',
    warrantyExpiry: '2028-04-10 (3 Years ProSupport NBD)',
    notes: 'AI & Data Science High-Performance Lab deployment.'
  },
  {
    id: 'PUR-2026-039',
    assetId: 'AST-201',
    assetName: 'All-in-One Desktop Core i7 Workstation (32GB RAM, 1TB SSD)',
    vendorId: 'VND-005',
    vendorName: 'Dell India Enterprise',
    categoryId: 'CAT-IT',
    categoryName: 'IT Hardware',
    subcategoryId: 'SUB-COM',
    subcategoryName: 'Computing & Workstations',
    itemType: 'All-in-One Desktop Core i7 Workstation',
    purchaseDate: '2026-01-30',
    purchasePrice: 74000.00,
    quantity: 15,
    totalAmount: 1110000.00,
    invoiceNumber: 'INV-DELL-2026-088',
    invoiceDate: '2026-01-27',
    warrantyExpiry: '2029-01-30 (3 Years ProSupport NBD)',
    notes: 'Cybersecurity & Cloud Computing specialized lab batch.'
  },
  {
    id: 'PUR-2024-040',
    assetId: 'AST-202',
    assetName: '24-Port Gigabit Managed PoE+ Network Switch',
    vendorId: 'VND-007',
    vendorName: 'Cisco Networks & IT Infrastructure',
    categoryId: 'CAT-IT',
    categoryName: 'IT Hardware',
    subcategoryId: 'SUB-NET',
    subcategoryName: 'Networking & Infrastructure',
    itemType: '24-Port Gigabit Managed PoE+ Network Switch',
    purchaseDate: '2024-06-18',
    purchasePrice: 38000.00,
    quantity: 6,
    totalAmount: 228000.00,
    invoiceNumber: 'INV-CSC-2024-092',
    invoiceDate: '2024-06-15',
    warrantyExpiry: '2029-06-18 (5 Years Enhanced Limited Lifetime)',
    notes: 'Core network backbone switches for Engineering Block Server Rack.'
  },
  {
    id: 'PUR-2025-041',
    assetId: 'AST-202',
    assetName: '24-Port Gigabit Managed PoE+ Network Switch',
    vendorId: 'VND-007',
    vendorName: 'Cisco Networks & IT Infrastructure',
    categoryId: 'CAT-IT',
    categoryName: 'IT Hardware',
    subcategoryId: 'SUB-NET',
    subcategoryName: 'Networking & Infrastructure',
    itemType: '24-Port Gigabit Managed PoE+ Network Switch',
    purchaseDate: '2025-07-22',
    purchasePrice: 41000.00,
    quantity: 8,
    totalAmount: 328000.00,
    invoiceNumber: 'INV-CSC-2025-315',
    invoiceDate: '2025-07-20',
    warrantyExpiry: '2030-07-22 (5 Years Enhanced Limited Lifetime)',
    notes: 'Campus Wi-Fi PoE power and smart classroom LAN integration.'
  },
  {
    id: 'PUR-2026-042',
    assetId: 'AST-202',
    assetName: '24-Port Gigabit Managed PoE+ Network Switch',
    vendorId: 'VND-007',
    vendorName: 'Cisco Networks & IT Infrastructure',
    categoryId: 'CAT-IT',
    categoryName: 'IT Hardware',
    subcategoryId: 'SUB-NET',
    subcategoryName: 'Networking & Infrastructure',
    itemType: '24-Port Gigabit Managed PoE+ Network Switch',
    purchaseDate: '2026-02-18',
    purchasePrice: 43500.00,
    quantity: 4,
    totalAmount: 174000.00,
    invoiceNumber: 'INV-CSC-2026-044',
    invoiceDate: '2026-02-15',
    warrantyExpiry: '2031-02-18 (5 Years Enhanced Limited Lifetime)',
    notes: 'Library Digital Resource Center & Admin wing network switches.'
  },
  {
    id: 'PUR-2024-043',
    assetId: 'AST-203',
    assetName: '27-inch 4K UHD IPS Professional Monitor',
    vendorId: 'VND-005',
    vendorName: 'Dell India Enterprise',
    categoryId: 'CAT-IT',
    categoryName: 'IT Hardware',
    subcategoryId: 'SUB-DIS',
    subcategoryName: 'Displays & Peripherals',
    itemType: '27-inch 4K UHD IPS Professional Monitor',
    purchaseDate: '2024-08-14',
    purchasePrice: 24500.00,
    quantity: 12,
    totalAmount: 294000.00,
    invoiceNumber: 'INV-DELL-2024-512',
    invoiceDate: '2024-08-11',
    warrantyExpiry: '2027-08-14 (3 Years Advanced Exchange)',
    notes: 'Design & Multimedia faculty workstations dual-monitor setup.'
  },
  {
    id: 'PUR-2025-044',
    assetId: 'AST-203',
    assetName: '27-inch 4K UHD IPS Professional Monitor',
    vendorId: 'VND-005',
    vendorName: 'Dell India Enterprise',
    categoryId: 'CAT-IT',
    categoryName: 'IT Hardware',
    subcategoryId: 'SUB-DIS',
    subcategoryName: 'Displays & Peripherals',
    itemType: '27-inch 4K UHD IPS Professional Monitor',
    purchaseDate: '2025-09-10',
    purchasePrice: 26000.00,
    quantity: 20,
    totalAmount: 520000.00,
    invoiceNumber: 'INV-DELL-2025-789',
    invoiceDate: '2025-09-08',
    warrantyExpiry: '2028-09-10 (3 Years Advanced Exchange)',
    notes: 'CAD / CAM Engineering Design Lab multi-display setup.'
  },
  {
    id: 'PUR-2026-045',
    assetId: 'AST-203',
    assetName: '27-inch 4K UHD IPS Professional Monitor',
    vendorId: 'VND-005',
    vendorName: 'Dell India Enterprise',
    categoryId: 'CAT-IT',
    categoryName: 'IT Hardware',
    subcategoryId: 'SUB-DIS',
    subcategoryName: 'Displays & Peripherals',
    itemType: '27-inch 4K UHD IPS Professional Monitor',
    purchaseDate: '2026-01-18',
    purchasePrice: 27200.00,
    quantity: 10,
    totalAmount: 272000.00,
    invoiceNumber: 'INV-DELL-2026-031',
    invoiceDate: '2026-01-15',
    warrantyExpiry: '2029-01-18 (3 Years Advanced Exchange)',
    notes: 'Research Scholar workstation monitors.'
  },
  {
    id: 'PUR-2024-046',
    assetId: 'AST-204',
    assetName: 'Online Modular Rackmount UPS 5KVA',
    vendorId: 'VND-003',
    vendorName: 'Matrix Electronics Care',
    categoryId: 'CAT-IT',
    categoryName: 'IT Hardware',
    subcategoryId: 'SUB-PWR',
    subcategoryName: 'Power & UPS',
    itemType: 'Online Modular Rackmount UPS 5KVA',
    purchaseDate: '2024-11-05',
    purchasePrice: 52000.00,
    quantity: 3,
    totalAmount: 156000.00,
    invoiceNumber: 'INV-MTR-2024-550',
    invoiceDate: '2024-11-02',
    warrantyExpiry: '2026-11-05 (2 Years Battery & Inverter)',
    notes: 'Clean zero-switchover power backup for Cloud & Virtualization racks.'
  },
  {
    id: 'PUR-2025-047',
    assetId: 'AST-204',
    assetName: 'Online Modular Rackmount UPS 5KVA',
    vendorId: 'VND-003',
    vendorName: 'Matrix Electronics Care',
    categoryId: 'CAT-IT',
    categoryName: 'IT Hardware',
    subcategoryId: 'SUB-PWR',
    subcategoryName: 'Power & UPS',
    itemType: 'Online Modular Rackmount UPS 5KVA',
    purchaseDate: '2025-11-20',
    purchasePrice: 55000.00,
    quantity: 4,
    totalAmount: 220000.00,
    invoiceNumber: 'INV-MTR-2025-880',
    invoiceDate: '2025-11-17',
    warrantyExpiry: '2027-11-20 (2 Years Battery & Inverter)',
    notes: 'Distributed server room UPS power protection.'
  },
  {
    id: 'PUR-2026-048',
    assetId: 'AST-204',
    assetName: 'Online Modular Rackmount UPS 5KVA',
    vendorId: 'VND-003',
    vendorName: 'Matrix Electronics Care',
    categoryId: 'CAT-IT',
    categoryName: 'IT Hardware',
    subcategoryId: 'SUB-PWR',
    subcategoryName: 'Power & UPS',
    itemType: 'Online Modular Rackmount UPS 5KVA',
    purchaseDate: '2026-02-05',
    purchasePrice: 58000.00,
    quantity: 2,
    totalAmount: 116000.00,
    invoiceNumber: 'INV-MTR-2026-077',
    invoiceDate: '2026-02-02',
    warrantyExpiry: '2028-02-05 (2 Years Battery & Inverter)',
    notes: 'Central NOC Room dedicated dual-conversion power unit.'
  }
];

